### PR TITLE
Made Changes To Footer

### PR DESCRIPTION
**Pull request by daemon-reconfig**
## Description

Made the changes mentioned in #1651 

## Changes
Removed:

1. Our organisation 
2. Follow us on Social Media
3. Subscribe to policy engine
4. EMAIL

## Screenshots

Screenshot 2024-05-26 at 11 51 53 PM

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this, @daemon-reconfig. I'll take the liberty of fixing the relevant merge conflicts before reviewing.

**Comment by daemon-reconfig** [comment]
Thank you so much 😊 @anth-volk

**Comment by anth-volk** [comment]
Currently in the process of reviewing this. Just for future reference, @dotslashbit, I did misspeak when I used the term "name" and meant "label" in the comments on the footer PR. The "name" property of an input is essential in JavaScript, as it's used within JavaScript for accessing items within a form.

**Comment by anth-volk** [comment]
Also, in the future, you have to periodically rebase your master off of PolicyEngine's master in order to keep them in sync. Yours is currently 167 commits behind ours, hence the merge conflict.

**Review by anth-volk — APPROVED** [review]
Thanks for your work on this, @daemon-reconfig. A few pieces of critique based on this contribution:

1. It's important to keep your `master` branch in line with ours by doing the following (if using the command line):
        1. Check that you have PolicyEngine as your upstream by running `git remote -v` and seeing if we're listed there
        2. If so, good; if not, clone our repo and run `git remote add upstream OUR_ADDRESS`
        3. Periodically, checkout your `master` branch, then run `git pull upstream master`. This will keep yours up-to-date
2. I've taken the liberty of reinstating the "Subscribe to PolicyEngine" because that's also part of a very similar component on the homepage. Considering how low-priority the changes, are, I think it's fine to leave it as a header instead of reworking everything so that one has the header and one doesn't
3. In your code, you left some commented bits that I had to remove; it's best to avoid doing that where possible
4. Your code had changes to `RadioButton` that emerged from a different PR. This is something that's come up a few times. When creating a new branch, it's best to go back to your `master` (so that none of your local changes are incorporated), then create your new feature or fix branch.

Thanks for your work on this. It should now be good to go.

**Comment by daemon-reconfig** [comment]
@anth-volk I will keep all of this in mind when making future contributions. Thank you for your hard work as well

**Pull request merged**
