### PR TITLE
removed pandas import

### LINKED ISSUE #1327: Remove unnecessary imports in `Reproduce in Python`
In the household page, Reproduce in Python starts with:
```python
from policyengine_us import Simulation
from policyengine_core.reforms import Reform
from policyengine_core.periods import instant
import pandas as pd
```
We don't need pandas in any simulation, and we only need `Reform` and `instant` when modeling a reform.

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description
fixes #1327 

removed pandas import

## Screenshots
Screenshot 2024-02-07 at 3 25 44 AM

### CODE REVIEW

**Comment by dotslashbit** [comment]
@MaxGhenis I was not sure if I should remove the simulation import too, so I have kept it there, if you want that to be removed then please let me know, thanks

**Comment by MaxGhenis** [comment]
Can you fix the other parts of #1327 while you're here?

**Comment by anth-volk** [comment]
Yes, @dotslashbit, please remove the Simulation import

**Comment by anth-volk** [comment]
@dotslashbit Unfortunately, as I've worked on this component before, this would actually break the policy calculator side of the app, as we do need the `Simulation` import there. I'd probably recommend a more comprehensive refactor, as this is a component that has seen quite a bit of change with time, and it'd be great to allow for easier updating when things change.

**Comment by dotslashbit** [comment]
@anth-volk ok then will look into it later this week

**Comment by MaxGhenis** [comment]
https://github.com/PolicyEngine/policyengine-app/issues/1334 would also be a quick fix to add to this

**Comment by anth-volk** [comment]
Hey @dotslashbit, I'm very sorry to do this, but as part of a more comprehensive refactor of the policy reproducibility sections, I opened a PR to fix #1327 and #1334, as they really need to be determined conditionally, and the refactor was comprehensive enough that it would be challenging to integrate any code changes you might have made. The refactor was part of a high-priority fix to issue #1337.

Again, I'm very sorry to do so, and I hope this isn't discouraging. Your contributions are highly valued, it was just out of necessity.

Closing.

**Comment by dotslashbit** [comment]
I can understand

**Pull request closed without merging**
