### PR TITLE
Re-enable cliff impacts

### LINKED ISSUE #1843: Re-enable cliff impacts

### LINKED ISSUE #1844: Remove hanging semicolon that renders on cliff impacts
Visible in the below screenshot; unclear where it's from

Screen Shot 2024-05-31 at 7 48 09 PM

### PR DESCRIPTION
**Pull request by anth-volk**
## Description

Fixes #1843.
Fixes #1844.

## Changes

This PR re-enables cliff impacts and removes the hanging semicolon present due to a syntax error in `PolicyOutput.jsx`.

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/14987227/b7713f1f-cc24-4c76-9842-035ed9910628

## Tests

N/A

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Can you show the hover? I'm curious what we show as the baseline cliff rates.

**Comment by MaxGhenis** [comment]
Just tried locally and getting these results. Something is off in our calculation, should be at least 1%. @nikhilwoodruff should we refactor using the new MTR code for LSRs?

Baseline for 2024:

| Dataset | Cliff rate | Cliff gap |
| - | - | - |
| ECPS | 0.26% | $620M |
| CPS | 0.20% | $416M |

**Comment by nikhilwoodruff** [comment]
Ah, yes we should which will probably block this for at least a couple of weeks.

**Comment by anth-volk** [comment]
@MaxGhenis Wanted to check if this is desired at all

**Comment by MaxGhenis** [comment]
Could we check the numbers again?

**Comment by anth-volk** [comment]
Sure, will do

**Comment by anth-volk** [comment]
@MaxGhenis Just attempted to re-run cliff impacts using these changes and our prod API, but I'm just getting a spinner. I'm guessing there's an issue in the API-side implementation.

**Comment by anth-volk** [comment]
This PR is so old that rebasing caused the above issue. I'll close this and open a new one, especially considering that this will probably require API-side changes, anyway.

**Pull request closed without merging**
