### PR TITLE
remove duplicate phrasing in estimated simulation runtime

### LINKED ISSUE #2034: Estimated runtime has duplicate phrasing
Shown here:

image

### PR DESCRIPTION
**Pull request by tawandamoyo**
## Changes
- Removed duplicate phrasing in estimated simulation runtime

## Tests

- Ran automated tests

### CODE REVIEW

**Review by anth-volk — CHANGES_REQUESTED** [review]
This is minor, but `momentjs` has been deprecated since 2020. On line 78, could you replace `moment` with another tool, perhaps by either doing the math manually or by finding a JS built-in method?

**Comment by tawandamoyo** [comment]
> This is minor, but `momentjs` has been deprecated since 2020. On line 78, could you replace `moment` with another tool, perhaps by either doing the math manually or by finding a JS built-in method?

sure, wrote a custom function, but `moment.js` is still used elsewhere .

**Comment by anth-volk** [comment]
Yeah, I figure it best to remove the deprecated function where and when we make edits to the relevant code portions, but I believe this was newly added.

**Review by anth-volk — APPROVED** [review]
This looks perfect @tawandamoyo! Thanks for your work on this.

**Pull request merged**
