### PR TITLE
added a close option

### LINKED ISSUE #1428: Allow "find an existing policy" box to be closed
At the moment, if the user opens this box on the right-hand sidebar, there's no option for closing it

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes #1428 

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/46224156/463ccddf-7e3d-4427-880e-9d2b1bf8e37c

### CODE REVIEW

**Comment by anth-volk** [comment]
@dotslashbit Before reviewing this - does the right-hand panel always have the strange white border around the reforms for you? And if so, which browser are you on?

**Comment by dotslashbit** [comment]
@anth-volk yes, it still shows that white border even though I'm executing localhost from the master branch. I'm using Firefox on MacBook Air m2

**Comment by anth-volk** [comment]
Does it occur for you when loading the live app, as well, or only when running locally?

**Comment by anth-volk** [comment]
Just figured it out: do you have an option enabled to always show scrollbars on your MacBook? If so, I think what's happening is that these have `overflow` set to `scroll`, as opposed to `overflow-y`. I'll submit a new issue on this.

Otherwise, I'm going to wait a few hours to review this, as I want to pitch a different approach to fixing the right-hand sidebar this that's a bit less piecemeal. If you'd be willing, I'm thinking something like what you've done for #1426, but for this, as well, but I need to pitch the idea first.

**Comment by dotslashbit** [comment]
Its not in always mode
Screenshot 2024-03-18 at 21 39 14

**Comment by anth-volk** [comment]
That is puzzling. Even so, I was able to reproduce by:
1. Setting my scrollbars to always on (that allowed me to see them)
2. Removing the relevant scroll options, which removed the unnecessary bars entirely

**Comment by anth-volk** [comment]
Unfortunately, I'm going to close this (and the original issue) in light of #1485. Thanks for your work on this, Sahil.

**Pull request closed without merging**
