### PR TITLE
Adjust headline size based on screen size

### LINKED ISSUE #757: Homepage headline doesn't fit in box on mobile

### PR DESCRIPTION
**Pull request by ductbuix**
Fix #757 by adjusting headline font size for mobile view and its responsive container.

### Summary
📱🛠️🎨

Enhanced the design and functionality of the `Hero` component on the home page. Made it adapt to different screen sizes and resolutions using `src/redesign/components/HomeLanding.jsx`.

> _The `Hero` component was too plain_
> _It needed some tweaks to look sane_
> _On different devices_
> _It had some vices_
> _But now it adapts to the screen_

### Walkthrough
*  Adjust the height and width of the `Hero` and `HeroText` components to be responsive to the screen size ([link](https://github.com/PolicyEngine/policyengine-app/pull/849/files?diff=unified&w=0#diff-049ddc39122e42841d7c31f8f1fac2971825ee2ff9304da4053acfb51658e045L108-R108), [link](https://github.com/PolicyEngine/policyengine-app/pull/849/files?diff=unified&w=0#diff-049ddc39122e42841d7c31f8f1fac2971825ee2ff9304da4053acfb51658e045L123-R124))
*  Reduce the font size of the `HeroTitle` component on mobile to avoid text wrapping or clipping ([link](https://github.com/PolicyEngine/policyengine-app/pull/849/files?diff=unified&w=0#diff-049ddc39122e42841d7c31f8f1fac2971825ee2ff9304da4053acfb51658e045L133-R133))

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Thanks for this @ductbuix- just testing it out locally I get this though- any ideas? 
image

**Review by nikhilwoodruff — COMMENTED** [review]
^

**Review by nikhilwoodruff — CHANGES_REQUESTED** [review]
.

**Comment by ductbuix** [comment]
> Thanks for this @ductbuix- just testing it out locally I get this though- any ideas? image

@nikhilwoodruff  Can you give me more information (screen size, or any condition)? I've tried several responsive sizes but it works still well.

**Comment by anth-volk** [comment]
Could this at all be a Safari thing? I know you test in Safari, @nikhilwoodruff, and I've found in the past that I have to use more workarounds, vendor prefixes, etc., when working with it.

**Comment by anth-volk** [comment]
Interestingly, post-changes, I don't get what Nikhil had mentioned, but I do get this at around 960px:

Screen Shot 2023-11-27 at 1 07 34 PM

**Comment by ductbuix** [comment]
> Could this at all be a Safari thing? I know you test in Safari, @nikhilwoodruff, and I've found in the past that I have to use more workarounds, vendor prefixes, etc., when working with it.

Oh, yes! I see, the Safari, let me take a look on it.

> Interestingly, post-changes, I don't get what Nikhil had mentioned, but I do get this at around 960px:

Yea, I initially focused on the issue title so I've only fixed for mobile.

So I will try to figure out what happened with Safari and fix the responsive for all screen. Btw, tell me if you know anything about why it broke in the Safari. @nikhilwoodruff @anth-volk

**Comment by nikhilwoodruff** [comment]
Thanks so much @ductbuix. Not sure I have any useful details to add on the root cause but let me know if you can't reproduce it.

**Comment by ductbuix** [comment]
> Thanks so much @ductbuix. Not sure I have any useful details to add on the root cause but let me know if you can't reproduce it.

Yea, I found the issue, but the fix might need some more changes. I'm on it.

**Comment by ductbuix** [comment]
Hi @anth-volk @nikhilwoodruff , I've fixed the responsive header, please check it out.

**Comment by nikhilwoodruff** [comment]
Looks great on my machine, thanks @ductbuix! @anth-volk I think the merge conflict is from your PR, would you mind taking a look at it?

**Review by nikhilwoodruff — APPROVED** [review]
Good to merge upon the merge conflict being resolved

**Comment by ductbuix** [comment]
> Good to merge upon the merge conflict being resolved

@nikhilwoodruff It looks good now.

**Pull request merged**
