### PR TITLE
Changed positive colors to green

### PR DESCRIPTION
**Pull request by martinyis**
I changed as asked all positives from DARK_GRAY to DARK_GREEN. Lmk if I need to redo it.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Could you drop a screenshot?

**Comment by martinyis** [comment]
green_01
green_02
`

**Comment by MaxGhenis** [comment]
Screenshot of the app please

**Comment by MaxGhenis** [comment]
Thanks for working on this @martinyis. Closing since we merged #344 to address it.

**Pull request closed without merging**
