### PR TITLE
fix: all pages have their unique title

### LINKED ISSUE #1040: Pages on the navbar do not have unique titles
For at least any pages created post-redesign (About, Research, Donate), the pages themselves have no distinct page title, instead merely displaying "PolicyEngine" on the browser tab.

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

closes #1040 

## Changes

Used useEffect to update page titles

## Screenshots
Screenshot 2024-01-09 at 10 19 18 AM
Screenshot 2024-01-09 at 10 19 08 AM
Screenshot 2024-01-09 at 10 18 59 AM

### CODE REVIEW

**Review by anth-volk — CHANGES_REQUESTED** [review]
Apologies @dotslashbit, perhaps I should've provided more guidance on this. Typically we format page titles as "*something* | PolicyEngine". Could you update these so that the page name is followed by the bar and PolicyEngine? Otherwise all looks good, thanks so much.

**Comment by dotslashbit** [comment]
@anth-volk I have updated the titles, please take a look

**Review by anth-volk — CHANGES_REQUESTED** [review]
If you could just run lint on this, I think it'll be good to merge, thanks @dotslashbit.

**Comment by anth-volk** [comment]
Perhaps I was ambiguous above; our lint command is `make format`, as this runs on all files

**Comment by dotslashbit** [comment]
@anth-volk `make format` isn't doing anything, it keeps README file unchanged

**Comment by anth-volk** [comment]
@dotslashbit Could you copy and paste your terminal output? On something I worked on, I also received an indication that README needed formatting, but my run of `make format` was successful.

**Comment by dotslashbit** [comment]
Here's the terminal output after running `make format`
```
black . -l 79
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install "black[jupyter]"``
All done! ✨ 🍰 ✨
4 files left unchanged.
npm run fix

> policyengine-app@0.1.0 fix
> eslint --fix --ext js,jsx . && prettier -w .

.eslintrc.json 25ms (unchanged)
.github/dependabot.yml 13ms (unchanged)
.github/PULL_REQUEST_TEMPLATE.md 16ms (unchanged)
.github/workflows/pr.yml 3ms (unchanged)
.github/workflows/push.yml 3ms (unchanged)
.prettierrc.json 1ms (unchanged)
gcp/app.yaml 0ms (unchanged)
jest.config.js 4ms (unchanged)
jsconfig.json 1ms (unchanged)
package-lock.json 112ms (unchanged)
package.json 1ms (unchanged)
public/index.html 24ms (unchanged)
public/manifest.json 1ms (unchanged)
README.md 9ms (unchanged)
src/__tests__/BaselineAndReformChart.test.js 5ms (unchanged)
src/__tests__/Buttons.test.js 3ms (unchanged)
src/__tests__/CountChildren.test.js 19ms (unchanged)
src/__tests__/CreateDefaultHousehold.test.js 2ms (unchanged)
src/__tests__/Dialogs.test.js 5ms (unchanged)
src/__tests__/HouseholdOutput.test.js 5ms (unchanged)
src/__tests__/InputField.test.js 3ms (unchanged)
src/__tests__/MarginalTaxRates.test.js 2ms (unchanged)
src/__tests__/MaritalStatus.test.js 4ms (unchanged)
src/__tests__/VariableEditor.test.js 3ms (unchanged)
src/api/analytics.js 1ms (unchanged)
src/api/call.js 5ms (unchanged)
src/api/charts.js 0ms (unchanged)
src/api/parameters.js 6ms (unchanged)
src/api/variables.js 17ms (unchanged)
src/controls/ArrowButton.jsx 1ms (unchanged)
src/controls/Button.jsx 2ms (unchanged)
src/controls/InputField.jsx 3ms (unchanged)
src/controls/LinkButton.jsx 2ms (unchanged)
src/controls/RadioButton.jsx 2ms (unchanged)
src/controls/SearchOptions.jsx 1ms (unchanged)
src/controls/SearchParamNavButton.jsx 1ms (unchanged)
src/controls/StableInputNumber.jsx 1ms (unchanged)
src/data/constants.js 0ms (unchanged)
src/data/countChildrenVars.js 2ms (unchanged)
src/data/countries.js 1ms (unchanged)
src/data/defaultHouseholds.js 1ms (unchanged)
src/data/reformDefinitionCode.js 1ms (unchanged)
src/index.js 1ms (unchanged)
src/lang/format.js 1ms (unchanged)
src/lang/plotly_locales/locale-en-gb.js 1ms (unchanged)
src/lang/plotly_locales/locale-en-us.js 1ms (unchanged)
src/layout/BiPanel.jsx 3ms (unchanged)
src/layout/BlogPostHolder.jsx 4ms (unchanged)
src/layout/BottomCarousel.jsx 2ms (unchanged)
src/layout/CenteredMiddleColumn.jsx 1ms (unchanged)
src/layout/CodeBlock.jsx 2ms (unchanged)
src/layout/CookieConsent.jsx 4ms (unchanged)
src/layout/CountrySelector.jsx 2ms (unchanged)
src/layout/DesktopView.jsx 1ms (unchanged)
src/layout/Divider.jsx 1ms (unchanged)
src/layout/EmailSignup.jsx 3ms (unchanged)
src/layout/Error.jsx 1ms (unchanged)
src/layout/FadeIn.jsx 0ms (unchanged)
src/layout/FolderPage.jsx 6ms (unchanged)
src/layout/Footer.jsx 3ms (unchanged)
src/layout/forms/FormContext.jsx 2ms (unchanged)
src/layout/forms/FormItem.jsx 2ms (unchanged)
src/layout/Header.jsx 5ms (unchanged)
src/layout/HoverCard.jsx 3ms (unchanged)
src/layout/LoadingCentered.jsx 1ms (unchanged)
src/layout/MarkdownPage.jsx 1ms (unchanged)
src/layout/Menu.jsx 4ms (unchanged)
src/layout/MobileCalculatorPage.jsx 14ms (unchanged)
src/layout/MobileView.jsx 0ms (unchanged)
src/layout/Responsive.jsx 1ms (unchanged)
src/layout/ResponsiveComponent.jsx 0ms (unchanged)
src/layout/ResultActions.jsx 2ms (unchanged)
src/layout/ResultsPanel.jsx 1ms (unchanged)
src/layout/Screenshottable.jsx 1ms (unchanged)
src/layout/SmallForm.jsx 2ms (unchanged)
src/layout/SocialLinks.jsx 2ms (unchanged)
src/layout/Spinner.jsx 0ms (unchanged)
src/layout/StackedMenu.jsx 1ms (unchanged)
src/layout/ThreeColumnPage.jsx 1ms (unchanged)
src/layout/WindowHeight.jsx 0ms (unchanged)
src/pages/AboutPage.jsx 2ms (unchanged)
src/pages/BlogPage.jsx 4ms (unchanged)
src/pages/CountryPackageDocs.jsx 1ms (unchanged)
src/pages/DonatePage.jsx 2ms (unchanged)
src/pages/FOF.jsx 1ms (unchanged)
src/pages/home/GitHubActivity.jsx 21ms (unchanged)
src/pages/HomePage.jsx 21ms (unchanged)
src/pages/household/HouseholdIntro.jsx 0ms (unchanged)
src/pages/household/HouseholdRightSidebar.jsx 4ms (unchanged)
src/pages/household/input/CountChildren.jsx 3ms (unchanged)
src/pages/household/input/MaritalStatus.jsx 3ms (unchanged)
src/pages/household/input/VariableEditor.jsx 7ms (unchanged)
src/pages/household/output/EarningsVariation.jsx 4ms (unchanged)
src/pages/household/output/EarningsVariation/BaselineAndReformChart.jsx 7ms (unchanged)
src/pages/household/output/EarningsVariation/BaselineOnlyChart.jsx 3ms (unchanged)
src/pages/household/output/EarningsVariation/cliffs.jsx 2ms (unchanged)
src/pages/household/output/EarningsVariation/convertToCurrencyString.js 1ms (unchanged)
src/pages/household/output/HouseholdOutput.jsx 3ms (unchanged)
src/pages/household/output/HouseholdReproducibility.jsx 2ms (unchanged)
src/pages/household/output/MarginalTaxRates.jsx 9ms (unchanged)
src/pages/household/output/NetIncomeBreakdown.jsx 5ms (unchanged)
src/pages/household/output/PoliciesModelledPopup.jsx 3ms (unchanged)
src/pages/household/output/PolicyImpactPopup.jsx 2ms (unchanged)
src/pages/household/output/RecreateHouseholdPopup.jsx 1ms (unchanged)
src/pages/household/output/tree.jsx 0ms (unchanged)
src/pages/household/VariableSearch.jsx 1ms (unchanged)
src/pages/HouseholdPage.jsx 8ms (unchanged)
src/pages/model/ModelDocumentation.jsx 6ms (unchanged)
src/pages/policy/input/ParameterEditor.jsx 3ms (unchanged)
src/pages/policy/input/ParameterOverTime.jsx 3ms (unchanged)
src/pages/policy/output/Analysis.jsx 7ms (unchanged)
src/pages/policy/output/budget/BudgetaryImpact.jsx 4ms (unchanged)
src/pages/policy/output/budget/DetailedBudgetaryImpact.jsx 5ms (unchanged)
src/pages/policy/output/CliffImpact.jsx 6ms (unchanged)
src/pages/policy/output/decile/AverageImpactByDecile.jsx 5ms (unchanged)
src/pages/policy/output/decile/AverageImpactByWealthDecile.jsx 2ms (unchanged)
src/pages/policy/output/decile/common.js 2ms (unchanged)
src/pages/policy/output/decile/IntraDecileImpact.jsx 4ms (unchanged)
src/pages/policy/output/decile/IntraWealthDecileImpact.jsx 1ms (unchanged)
src/pages/policy/output/decile/RelativeImpactByDecile.jsx 4ms (unchanged)
src/pages/policy/output/decile/RelativeImpactByWealthDecile.jsx 1ms (unchanged)
src/pages/policy/output/Display.jsx 8ms (unchanged)
src/pages/policy/output/FetchAndDisplayImpact.jsx 6ms (unchanged)
src/pages/policy/output/ImpactChart.jsx 3ms (unchanged)
src/pages/policy/output/ImpactTypes.jsx 1ms (unchanged)
src/pages/policy/output/InequalityImpact.jsx 4ms (unchanged)
src/pages/policy/output/LaborSupplyResponse.jsx 2ms (unchanged)
src/pages/policy/output/PolicyBreakdown.jsx 5ms (unchanged)
src/pages/policy/output/PolicyOutput.jsx 1ms (unchanged)
src/pages/policy/output/PolicyReproducibility.jsx 2ms (unchanged)
src/pages/policy/output/poverty/common.js 1ms (unchanged)
src/pages/policy/output/poverty/DeepPovertyImpact.jsx 1ms (unchanged)
src/pages/policy/output/poverty/DeepPovertyImpactByGender.jsx 1ms (unchanged)
src/pages/policy/output/poverty/PovertyChangeContext.jsx 0ms (unchanged)
src/pages/policy/output/poverty/PovertyImpact.jsx 3ms (unchanged)
src/pages/policy/output/poverty/PovertyImpactByGender.jsx 6ms (unchanged)
src/pages/policy/output/poverty/PovertyImpactByRace.jsx 4ms (unchanged)
src/pages/policy/output/tree.js 1ms (unchanged)
src/pages/policy/output/utils.js 1ms (unchanged)
src/pages/policy/PolicyRightSidebar.jsx 10ms (unchanged)
src/pages/policy/PolicySearch.jsx 2ms (unchanged)
src/pages/PolicyPage.jsx 3ms (unchanged)
src/pages/PrivacyPage.jsx 1ms (unchanged)
src/pages/ResearchPage.jsx 1ms (unchanged)
src/pages/StatusPage.jsx 4ms (unchanged)
src/pages/statusPageDefaults.js 57ms (unchanged)
src/posts/analysing-autumn-budget-universal-credit-reforms-with-policyengine.md 20ms (unchanged)
src/posts/analysis-of-guaranteed-income-for-the-21st-century.md 22ms (unchanged)
src/posts/analysis-of-the-spring-budget-2023.md 9ms (unchanged)
src/posts/authors.json 0ms (unchanged)
src/posts/automate-policy-analysis-with-policy-engines-new-chatgpt-integration.md 21ms (unchanged)
src/posts/autumn-statement-2023.md 20ms (unchanged)
src/posts/breaking-down-policy-impacts-by-wealth-decile.md 14ms (unchanged)
src/posts/breaking-down-uk-poverty-impacts-by-sex.md 7ms (unchanged)
src/posts/breaking-down-us-poverty-impacts-by-sex.md 7ms (unchanged)
src/posts/building-the-roots-of-policyengine-nigeria.md 11ms (unchanged)
src/posts/california-income-tax.md 8ms (unchanged)
src/posts/charitable-contributions.md 4ms (unchanged)
src/posts/citizens-economic-council.md 7ms (unchanged)
src/posts/computing-your-oregon-earned-income-tax-credit.md 7ms (unchanged)
src/posts/dc-financial-support-for-families-with-children.md 22ms (unchanged)
src/posts/digital-public-goods-alliance-recognizes-policyengine-as-a-digital-public-good.md 5ms (unchanged)
src/posts/district-child-tax-credit.md 23ms (unchanged)
src/posts/electric-vehicle-tax-credits-under-current-law-and-the-inflation-reduction-act.md 4ms (unchanged)
src/posts/enhancing-the-current-population-survey-for-policy-analysis.md 20ms (unchanged)
src/posts/estimating-your-supplemental-security-income-benefits-in-policyengine.md 4ms (unchanged)
src/posts/fiscalsim.md 16ms (unchanged)
src/posts/from-idea-to-impact-scoring-a-policy-reform-on-the-new-policyengine-uk.md 18ms (unchanged)
src/posts/from-idea-to-impact-scoring-a-policy-reform-on-the-new-policyengine-us.md 17ms (unchanged)
src/posts/from-openfisca-to-policyengine.md 9ms (unchanged)
src/posts/gpt-analysis.md 33ms (unchanged)
src/posts/how-developers-can-explore-the-policyengine-api.md 7ms (unchanged)
src/posts/how-machine-learning-tools-make-policyengine-more-accurate.md 22ms (unchanged)
src/posts/how-policyengine-estimates-the-effects-of-uk-carbon-taxes.md 17ms (unchanged)
src/posts/how-to-simulate-basic-and-guaranteed-income-policies-in-policyengine-us.md 25ms (unchanged)
src/posts/how-would-reforms-affect-cliffs.md 35ms (unchanged)
src/posts/impact-of-the-chancellors-cost-of-living-support-package.md 17ms (unchanged)
src/posts/income-tax-cuts-rishi-sunak-is-reportedly-considering.md 12ms (unchanged)
src/posts/introducing-utah-state-income-tax-analysis-on-policyengine.md 17ms (unchanged)
src/posts/kansas-flat-income-tax-sb-169.md 25ms (unchanged)
src/posts/kansas-income-tax.md 6ms (unchanged)
src/posts/make-everyone-a-policymaker.md 20ms (unchanged)
src/posts/malliotakis-steel-working-families-tax-cut-act.md 10ms (unchanged)
src/posts/maryland-standard-deduction.md 10ms (unchanged)
src/posts/massachusetts-governor-maura-healeys-fy-2024-budget-recommendation.md 28ms (unchanged)
src/posts/medlock-donation-calculator.md 12ms (unchanged)
src/posts/medlock-wins.md 6ms (unchanged)
src/posts/new-mexico-income-tax-launch.md 12ms (unchanged)
src/posts/new-york-tanf.md 7ms (unchanged)
src/posts/openfisca-wins-edge-of-government-innovation-award.md 8ms (unchanged)
src/posts/oregons-nonrefundable-exemption-credit.md 7ms (unchanged)
src/posts/policyengine-2022-year-in-review.md 17ms (unchanged)
src/posts/policyengine-at-the-basic-income-guarantee-conference-and-the-beeck-centers-rules-as-code-demo-day.md 6ms (unchanged)
src/posts/policyengine-comes-stateside.md 13ms (unchanged)
src/posts/policyengine-launches-in-new-york-state.md 4ms (unchanged)
src/posts/policyengine-launches-in-washington-state.md 7ms (unchanged)
src/posts/policyengines-2021-year-in-review.md 12ms (unchanged)
src/posts/posts.json 4ms (unchanged)
src/posts/poverty-race-ethnicity.md 5ms (unchanged)
src/posts/prime-minister-liz-trusss-energy-bill-price-cap.md 9ms (unchanged)
src/posts/projected-impact-of-the-uks-extended-energy-price-guarantee.md 8ms (unchanged)
src/posts/raising-the-marriage-allowance-from-10-to-100.md 19ms (unchanged)
src/posts/README.md 4ms (unchanged)
src/posts/reform-uks-emergency-recovery-plan.md 13ms (unchanged)
src/posts/repealing_the_two_child_limit.md 30ms (unchanged)
src/posts/restoration-of-the-american-rescue-plan-acts-expanded-child-tax-credit.md 19ms (unchanged)
src/posts/restoring-arpa-eitc.md 24ms (unchanged)
src/posts/rishi-sunaks-proposal-to-cut-the-basic-rate-to-16-percent.md 8ms (unchanged)
src/posts/stamp-duties-in-policyengine-uk.md 12ms (unchanged)
src/posts/tax-cuts-in-prime-minister-trusss-growth-plan.md 12ms (unchanged)
src/posts/the-child-tax-credit-in-2023.md 18ms (unchanged)
src/posts/the-green-party-manifesto-at-policyfest.md 13ms (unchanged)
src/posts/the-new-policyengine-us-population-impact-page.md 19ms (unchanged)
src/posts/uk-the-new-policyengine.md 7ms (unchanged)
src/posts/updating-policyengine-to-reflect-snap-reform-in-the-omnibus-bill.md 4ms (unchanged)
src/posts/us-the-new-policyengine.md 5ms (unchanged)
src/posts/winship-individualized-eitc.md 27ms (unchanged)
src/README.md 3ms (unchanged)
src/redesign/components/About.jsx 3ms (unchanged)
src/redesign/components/APIDocumentationPage.jsx 9ms (unchanged)
src/redesign/components/BlogPage.jsx 20ms (unchanged)
src/redesign/components/Calculator.jsx 2ms (unchanged)
src/redesign/components/CalculatorInterstitial.jsx 1ms (unchanged)
src/redesign/components/Carousel.jsx 2ms (unchanged)
src/redesign/components/CitizensEconomicCouncil.jsx 0ms (unchanged)
src/redesign/components/Contact.jsx 1ms (unchanged)
src/redesign/components/Donate.jsx 2ms (unchanged)
src/redesign/components/EmphasisedLink.jsx 0ms (unchanged)
src/redesign/components/FontIcon.jsx 0ms (unchanged)
src/redesign/components/Footer.jsx 3ms (unchanged)
src/redesign/components/Header.jsx 4ms (unchanged)
src/redesign/components/Home.jsx 1ms (unchanged)
src/redesign/components/HomeBlogPreview.jsx 8ms (unchanged)
src/redesign/components/HomeCallToAction.jsx 1ms (unchanged)
src/redesign/components/HomeLanding.jsx 1ms (unchanged)
src/redesign/components/HomePolicyEngineFeatures.jsx 0ms (unchanged)
src/redesign/components/HomeQuoteCarousel.jsx 4ms (unchanged)
src/redesign/components/HomeSubscribe.jsx 1ms (unchanged)
src/redesign/components/HomeTransparency.jsx 0ms (unchanged)
src/redesign/components/HomeUsedBy.jsx 2ms (unchanged)
src/redesign/components/HoverBox.jsx 2ms (unchanged)
src/redesign/components/Jobs.jsx 5ms (unchanged)
src/redesign/components/PageHeader.jsx 1ms (unchanged)
src/redesign/components/PolicyEngine.jsx 4ms (unchanged)
src/redesign/components/README.md 1ms (unchanged)
src/redesign/components/Research.jsx 5ms (unchanged)
src/redesign/components/Section.jsx 2ms (unchanged)
src/redesign/components/ShowcaseItem.jsx 1ms (unchanged)
src/redesign/components/Testimonials.jsx 1ms (unchanged)
src/redesign/components/TextBox.jsx 1ms (unchanged)
src/redesign/components/useCountryId.jsx 1ms (unchanged)
src/redesign/components/useDisplayCategory.jsx 1ms (unchanged)
src/redesign/data/Authors.jsx 1ms (unchanged)
src/redesign/data/Organisations.jsx 1ms (unchanged)
src/redesign/data/Posts.jsx 7ms (unchanged)
src/redesign/data/Quotes.jsx 2ms (unchanged)
src/redesign/data/Staff.jsx 1ms (unchanged)
src/redesign/style/App.css 5ms (unchanged)
src/redesign/style/colors.jsx 0ms (unchanged)
src/redesign/style/fonts.jsx 0ms (unchanged)
src/redesign/style/index.jsx 0ms (unchanged)
src/redesign/style/spacing.jsx 1ms (unchanged)
src/serviceWorker.js 1ms (unchanged)
src/serviceWorkerRegistration.js 2ms (unchanged)
src/style/App.css 3ms (unchanged)
src/style/colors.jsx 1ms (unchanged)
src/style/index.jsx 1ms (unchanged)
src/style/spacing.jsx 1ms (unchanged)
```

**Comment by anth-volk** [comment]
@dotslashbit I actually ran into this myself today. The key is to rebase off of an updated version of master. Basically, in editing the README, I accidentally added a new line, and since I had to edit it on GitHub itself (to add a new version of a photo), it was never linted before push.

**Review by anth-volk — APPROVED** [review]
This looks great! Thanks @dotslashbit.

**Pull request merged**
