### PR TITLE
Fix #438: Consistent y axis for poverty charts

### LINKED ISSUE #438: Use consistent y axis across poverty charts
Toggling between different poverty/deep poverty charts can mask differences because the y axis resets

### PR DESCRIPTION
**Pull request by QianruZhang78**
### Summary
📉📊🧑‍🤝‍🧑

Set the y-axis range for the poverty and deep poverty impact charts to be between -0.05 and 0.05. This improves the readability and consistency of the charts that show how different groups are affected by the policy reforms.

> _`y-axis` range set_
> _to show impact on poverty_
> _autumn of reform_

### Walkthrough
*  Set the y-axis range for the charts that show the percentage change in poverty or deep poverty rates by different groups to be between -0.05 and 0.05, based on the data values, to improve readability and consistency ([link](https://github.com/PolicyEngine/policyengine-app/pull/578/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8R75), [link](https://github.com/PolicyEngine/policyengine-app/pull/578/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cR69), [link](https://github.com/PolicyEngine/policyengine-app/pull/578/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33R73), [link](https://github.com/PolicyEngine/policyengine-app/pull/578/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fR67), [link](https://github.com/PolicyEngine/policyengine-app/pull/578/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbR80))

### CODE REVIEW

**Comment by QianruZhang78** [comment]
All y axis in poverty charts are now ranging from -5% to 5%. 
Screen Shot 2023-06-13 at 12 00 09 AM
Screen Shot 2023-06-13 at 12 00 15 AM

**Review by nikhilwoodruff — CHANGES_REQUESTED** [review]
Thanks for this @QianruZhang78 - sorry if the issue wasn't clear: could we instead make the poverty chart axis the smallest range possible that fits all data points in the five poverty charts, rather than a constant range? Essentially, the range `[lowest_relative_poverty_reduction, highest_relative_poverty_increase]`

**Comment by QianruZhang78** [comment]
> Thanks for this @QianruZhang78 - sorry if the issue wasn't clear: could we instead make the poverty chart axis the smallest range possible that fits all data points in the five poverty charts, rather than a constant range? Essentially, the range `[lowest_relative_poverty_reduction, highest_relative_poverty_increase]`

Sure thing, I've made the updates such that the y axis now uses the smallest range possible that fits all data points in the five poverty charts:) Please check and let me know if this works, thx.

**Comment by QianruZhang78** [comment]
> Sorry, last edit request I promise! The new logic looks good, I just realised about the scenarios:
> 
> * All the poverty changes are positive- the range should still start at zero
> * All the poverty changes are negative- the range should still end at zero
> 
> Could we change the logic to: `[min(min_poverty_change, 0), max(max_poverty_change, 0)]`. Thanks

Completely no worries, sorry for the late response I've added the update:)

**Review by nikhilwoodruff — APPROVED** [review]
Perfect, thanks @QianruZhang78 !

**Pull request merged**
