### PR TITLE
scroll is now going to the top

### LINKED ISSUE #1235: Ensure variable input pages in household and policy calculators scroll to top on render
Every time the variable is changed, the user should be at the top of the page

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes #1235 

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/46224156/1adcf54e-7653-454a-9be2-74de2742326d

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks, will review later today

**Review by anth-volk — CHANGES_REQUESTED** [review]
I'm sorry @dotslashbit, perhaps the open issue wasn't very clear. In #1235, what we're hoping is that when a user is on, let's say IRS tax bracket 5, and clicks on tax bracket 3, that when the page to alter tax bracket 3 loads, the user will be at the top of it. At the moment, if you're at the bottom of tax bracket 5's page and click on 3, you'll load in at the bottom of 3, which is confusing to the UI. 

We actually don't have a preferred behavior for the left-hand bar, but it would probably be to scroll and place the current selected parameter at the top or the middle? Either way, we aren't looking to change how it works currently.

Would you mind redoing this so that it's focused on the page in the editor?

**Comment by dotslashbit** [comment]
@anth-volk In the tax bracket 5 page, there's no scroll. Can you please, give me the link for the above scenario, so that I can test my changes.

**Comment by anth-volk** [comment]
@dotslashbit Huh, incredibly, you're right, it no longer seems to scroll. A better example of this behavior is as follows:

1. Visit the "Individual income tax rate thresholds" page at https://policyengine.org/us/policy?focus=gov.irs.income.bracket.thresholds&reform=47002&region=us&timePeriod=2024&baseline=2
2. Scroll all the way to the bottom
3. On the left-hand bar, click on "Individual income tax rates", just above the bolded "Individual income tax rate thresholds" link

You'll be on the bottom of that page. We're hoping to prevent that and scroll the user to the top on load.

**Comment by dotslashbit** [comment]
@anth-volk Okay, so just to clarify there's no scroll for the middle column


https://github.com/PolicyEngine/policyengine-app/assets/46224156/127290fb-d62e-4c74-b90f-89196b5f7c1b

**Comment by anth-volk** [comment]
@dotslashbit Unfortunately your video appears to be broken. Could you elaborate on your question?

**Comment by dotslashbit** [comment]
@anth-volk I went to that link but still there's no scroll for the middle column.
If possible can you share a video

**Comment by anth-volk** [comment]
@dotslashbit Do you happen to know the height of the display you're on? That said, yeah, I'll record something when able

**Comment by anth-volk** [comment]
Here's the behavior I was describing:


https://github.com/PolicyEngine/policyengine-app/assets/14987227/14c05999-a5b0-47bd-b8f9-1b1a922a9f07

**Comment by anth-volk** [comment]
Closing as stale

**Pull request closed without merging**
