### PR TITLE
Refactor: Donate.jsx

### PR DESCRIPTION
**Pull request by amar9312**
Resolves issue [776](https://github.com/PolicyEngine/policyengine-app/issues/776)

Changes:
* Wrap `<LinkButton` inside `<Link>`
* Set `link` prop of `<LinkButton` to `""`
* Remove `noArrow` prop of `<LinkButton`

npm test:
`No tests found related to files changed since last commit.`

### CODE REVIEW

**Comment by anth-volk** [comment]
Will be getting to this tomorrow. I think we can extrapolate this change and simply implement it within LinkButton itself. Thanks for this, really clean fix.

**Comment by amar9312** [comment]
> Will be getting to this tomorrow. I think we can extrapolate this change and simply implement it within LinkButton itself. Thanks for this, really clean fix.

I agree with that. The LinkButton should have this feature.

**Comment by anth-volk** [comment]
Apologies on the delays, but will get to this early next week

**Review by anth-volk — APPROVED** [review]
I took the liberty of simply moving your changes up to the LinkButton component itself, but the logic behind it remains yours. Thanks so much for your work @amar9312.

**Comment by anth-volk** [comment]
This fails a test that was written against the old implementation. If you'd like to change it, please feel free, but I'm also happy to do so, likely tomorrow

**Review by anth-volk — CHANGES_REQUESTED** [review]
Need to change LinkButton's test

**Review by anth-volk — APPROVED** [review]
Thanks again for the contributions, @amar9312. Now that this is factored out into the overall component, we've added a bit more accessibility to the app overall.

**Comment by MaxGhenis** [comment]
Thanks @amar9312! Heads up if you type `Resolves #776` or `Fixes #776` in the first comment, it will link the issue so that merging the PR closes the issue. The way you did it does not link it, so I closed the issue manually.

**Pull request merged**
