### PR TITLE
Added route for API embed

### LINKED ISSUE #1710: Show API status dashboard from API page
I think we used to have a URL like https://policyengine.org/us/api-status that embedded https://policyengine.betteruptime.com/ but I don't see it now. Let's embed it directly in https://policyengine.org/us/api

### PR DESCRIPTION
**Pull request by czhou578**
## Description

Fixes #1710 

## Changes

Added the route for the API dashboard status embed into the app.

## Screenshots

image

## Tests

No new tests added.

### CODE REVIEW

**Review by anth-volk — CHANGES_REQUESTED** [review]
@czhou578 This is great, thank you very much. I know this wasn't in the initial issue, but would you also be willing to do the following minor thing:

The iframe that the BetterStack display sits in adds that second scrollbar in the screenshot you provided. Could you increase its height from 800px to 1000px?

You'll also notice that the `/calculate` endpoint looks like it fails, even though it actually succeeds. This is because the component uses a hard-coded sample household that is no longer valid. I think that will require deleting particular parts of the default, and it would be hard to describe exactly what should be done, so if you'd be willing, I'll open an issue after the status page is restored, and I'll take that one on myself.

Thanks again!

**Comment by czhou578** [comment]
@anth-volk Done.

**Comment by anth-volk** [comment]
My apologies for losing track of this. Will review.

**Review by anth-volk — APPROVED** [review]
Thanks so much for this, @czhou578! Great to have this monitoring available again.

**Pull request merged**
