### PR TITLE
Autumn Statement 2023 analysis

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
### Summary
📝📊💰

This pull request adds a new blog post to the PolicyEngine website, which analyses the potential impact of the reported tax and benefit reforms in the Autumn Statement 2023. The post is created in `src/posts/autumn-statement-2023-pre-briefing.md` and its metadata is added to `src/redesign/data/Posts.jsx`.

> _New blog post added_
> _`PolicyEngine` simulates_
> _Autumn reforms_

### Walkthrough
* Add a new blog post analysing the Autumn Statement 2023 ([link](https://github.com/PolicyEngine/policyengine-app/pull/847/files?diff=unified&w=0#diff-0ab7cca90de4dc4caf22183c55513110fd77f7cde43c7dddf3b91de25a312802L1-R21), [link](https://github.com/PolicyEngine/policyengine-app/pull/847/files?diff=unified&w=0#diff-d7f968da73057074482e4a9ec4b1bb901b56c1487a4a6aebcc4d8648ea2ecc3aR708-R717))

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Figure 1: 
image

**Comment by nikhilwoodruff** [comment]
Figure 2 
image

**Comment by nikhilwoodruff** [comment]
Figure 3: 
image

**Comment by MaxGhenis** [comment]
# NI
[Effect of NI reform on a single person](https://policyengine.org/uk/household?focus=householdOutput.earnings&reform=37170&region=uk&timePeriod=2023&baseline=1&household=32608)
image

# Benefit uprating

## Households

[Effect of combined benefit uprating on a single person](https://policyengine.org/uk/household?focus=householdOutput.earnings&reform=37185&region=uk&timePeriod=2023&baseline=1&household=32608) @nikhilwoodruff what's the £10 change?
image

[on a family of four](https://policyengine.org/uk/household?focus=householdOutput.earnings&reform=37185&region=uk&timePeriod=2023&baseline=1&household=35960) (£136 plateau)
image

[couple of 70yos](https://policyengine.org/uk/household?focus=householdOutput.earnings&reform=37185&region=uk&timePeriod=2023&baseline=1&household=35963) (£10 plateau again)
image

## Society

[outcomes](https://policyengine.org/uk/policy?focus=policyOutput.intraDecileImpact&reform=37185&region=uk&timePeriod=2023&baseline=1)
image

[poverty](https://policyengine.org/uk/policy?focus=policyOutput.povertyImpact&reform=37185&region=uk&timePeriod=2023&baseline=1)
image

[income inequality](https://policyengine.org/uk/policy?focus=policyOutput.inequalityImpact&reform=37185&region=uk&timePeriod=2023&baseline=1)
image

[cliffs](https://policyengine.org/uk/policy?focus=policyOutput.cliffImpact&reform=37185&region=uk&timePeriod=2023&baseline=1)
image

**Comment by nikhilwoodruff** [comment]
image

**Comment by MaxGhenis** [comment]
Limiting to NI reforms

https://policyengine.org/uk/policy?focus=policyOutput.decileAverageImpact&reform=37636&region=uk&timePeriod=2024&baseline=1
image

https://policyengine.org/uk/policy?focus=policyOutput.decileRelativeImpact&reform=37636&region=uk&timePeriod=2024&baseline=1
image

https://policyengine.org/uk/policy?focus=policyOutput.intraDecileImpact&reform=37636&region=uk&timePeriod=2024&baseline=1
image

https://policyengine.org/uk/policy?focus=policyOutput.povertyImpact&reform=37636&region=uk&timePeriod=2024&baseline=1
image

https://policyengine.org/uk/policy?focus=policyOutput.inequalityImpact&reform=37636&region=uk&timePeriod=2024&baseline=1
image

**Pull request merged**
