### PR TITLE
Edit VAT school Post

### PR DESCRIPTION
**Pull request by vahid-ahmadi**
We changed the calibration for schools in our model. I need to update the numbers and graphs in VAT school post.

### CODE REVIEW

**Review by nikhilwoodruff — APPROVED** [review]
- [ ] Update charts to match PE live site
- [ ] Update description to match PE

**Review by nikhilwoodruff — CHANGES_REQUESTED** [review]
Recent approve was a mistake! Needs those tick boxes

**Comment by vahid-ahmadi** [comment]
Fixes #2135

**Review by nikhilwoodruff — APPROVED** [review]

**Comment by anth-volk** [comment]
@vahid-ahmadi For future reference, you have to add "Fixes NUMBER", like you did, to the description of the PR. If you add it lower down, it won't correctly close the issue.

**Pull request merged**
