### PR TITLE
Changed Border color to white

### PR DESCRIPTION
**Pull request by daemon-reconfig**
## Description
Fixes: #912 
Changed unselected button's border color to white instead of grey

## Screenshots
Screenshot 2024-04-20 at 5 42 36 PM

### CODE REVIEW

**Comment by anth-volk** [comment]
Please add "Fixes #something" to the description

**Comment by daemon-reconfig** [comment]
done

**Comment by anth-volk** [comment]
Perfect, thank you. I'll review early tomorrow.

**Comment by daemon-reconfig** [comment]
thank you!

**Comment by daemon-reconfig** [comment]
I have accepted the invitation and I am available anytime this week. we can connect whenever you are free and our times coincide.

**Comment by anth-volk** [comment]
Thanks again for this @daemon-reconfig. This was actually fixed as part of #1670, due to an update to Ant Design v5, which enabled some easier fixes here, but we do appreciate your work on this.

**Comment by daemon-reconfig** [comment]
sure. thanks it was a great experience

**Pull request closed without merging**
