### PR TITLE
Replace baseline+net vs diff switch with a radio button component #78

### PR DESCRIPTION
**Pull request by nung22**

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks @nung22! Could you please add a screenshot and/or screen recording of it in action?

**Comment by nung22** [comment]
policy-engine-issue-78
Here's a gif of the new tab-style radio button!

**Comment by nikhilwoodruff** [comment]
Thanks @nung22! This is helpful, OK so two minor requests:
* Could we use the same blue as the rest of the app (and the chart)? There's a `const BLUE = ...` in the repo.
* Could we also make sure the padding between the bottom of the radio button component and the start of the chart legends is the same so the chart isn't jumping up and down too much?

**Comment by MaxGhenis** [comment]
Could you remove `Show` from the radio button labels?

**Review by nikhilwoodruff — APPROVED** [review]

**Comment by nung22** [comment]
v3
@MaxGhenis Here it is with `Show` removed from radio button labels

**Comment by nikhilwoodruff** [comment]
Thanks @nung22. Merging now

**Pull request merged**
