### PR TITLE
refactor Analysis.jsx component

### LINKED ISSUE #1751: Refactor `Analysis.jsx` so that the prompt sits in its own file
This would allow easier editing, easier conditional implementation of various different prompts (if we go that way), etc. Note: This should be done after Friday, May 10.

### PR DESCRIPTION
**Pull request by anmolchhabra21**
## Description

Fixes #1751 

## Changes

Refactored analysis.jsx component

## Screenshots

image

## Tests

17/17 passed: 
image

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this @anmolchhabra21. Will review later today.

**Comment by anmolchhabra21** [comment]
Thanks, @anth-volk, 
But have we made any changes to our CI pipeline? It showed some errors in the makefile, but I haven't changed it.

**Comment by anth-volk** [comment]
That is due to some API issues we’re having at the moment that should be fixed soon

**Review by anth-volk — APPROVED** [review]
Thanks for this, @anmolchhabra21, I think these changes would enable us to potentially conditionally employ one of a variety of prompts in the future. Much appreciated.

**Pull request merged**
