### PR TITLE
Extend the cliffs in the Earnings Variation chart to meet its horizontal borders

### LINKED ISSUE #978: Extend the cliffs in the Earnings Variation chart to meet its horizontal borders
In this [example](https://policyengine.org/us/household?focus=householdOutput.earnings&household=38027), the cliffs get truncated at `0` and `150,000`:

Screenshot 2023-12-18 at 10 43 49 AM

### PR DESCRIPTION
**Pull request by abhcs**
Fix #978 by passing the y-axis range to the `getCliffs` function.

Tested against [this household](https://policyengine.org/us/household?focus=householdOutput.earnings&household=38027). Now, the chart looks like this:

Screenshot 2023-12-18 at 11 17 55 AM

### CODE REVIEW

**Comment by abhcs** [comment]
While this is an acceptable solution, I think we may be able to do better by using `yref`. Hence I am converting the PR to draft.

**Comment by abhcs** [comment]
Ideally, we should use Plotly *shapes* and not *plots* for cliffs because they are just annotations. Shapes also support "paper" coordinates using `yref`, for instance. This is what we want for the y-coordinates of the cliff. However, Plotly shapes do not support hover text at the moment, as far as I can tell. Therefore, I am still passing the y-axis range to the `getCliffs` function, as mentioned in the PR description.

**Comment by MaxGhenis** [comment]
This looks a bit strange to me going negative. Could you bound the x and y axes at zero in cases where the data doesn't contain negative values? We'd like to do that regardless.

**Comment by abhcs** [comment]
Are you sure you want zero padding when there are only nonnegative values? If I make it zero then we get:

Screenshot 2023-12-21 at 2 26 10 PM

The zeros are colliding. We can also do a smaller padding when there are only nonnegative values:

Screenshot 2023-12-21 at 2 29 33 PM

Which image do you prefer: top or bottom?

**Comment by abhcs** [comment]
We can also reduce the padding everywhere from `10%` to `1%` of the length of the range of values, which would yield:

Screenshot 2023-12-21 at 2 34 52 PM

Another option to consider.

**Comment by MaxGhenis** [comment]
your most recent suggestion looks good, thanks

**Comment by MaxGhenis** [comment]
Ah actually could we set the y axis minimum to zero? The cliff shading extends beyond the x axis as is. We can keep the 1% margin for the x axis minimum so the dot remains visible (baseline net income is usually >0 so shouldn't be an issue for the other).

**Comment by abhcs** [comment]
I can ensure that the cliff starts at zero in the above image if that is the only objection and leave the padding unchanged.

**Comment by abhcs** [comment]
After latest commit:

Screenshot 2023-12-21 at 6 22 24 PM

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
