### PR TITLE
Rename `organisations` to `organizations` to align spelling with American English standards

### LINKED ISSUE #2229: Rename `organisations` to `organizations` in `HomeUsedBy` and the data file's filepath
Continue Americanizing spelling by doing this

### PR DESCRIPTION
**Pull request by TimYaTingChen**
## Description

Fixes #2229

## Changes

Rename `organisations` to `organizations` to align spelling with American English standards.

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for your contribution @TimYaTingChen! Will review this later today and get back to you then.

**Comment by anth-volk** [comment]
@TimYaTingChen My apologies, solving a bug took over my calendar a bit, and so I should get to this Thursday.

**Comment by TimYaTingChen** [comment]
@anth-volk No problem at all! I appreciate you keeping me updated. I’ll be here if there’s anything you need from me when you review the PR. Thanks again!

**Review by anth-volk — APPROVED** [review]
Thanks for this @TimYaTingChen! Just ran locally to make sure everything worked alright. Approved!

**Pull request merged**
