### PR TITLE
fix: updated the donate link

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

Please provide a summary of the changes and which issue is fixed. Please include relevant motivation and context.

Fixed: [#970](https://github.com/PolicyEngine/policyengine-app/issues/970)

## Changes
Modified the Header.jsx component and added the new link to both the page and left navigation 
functions.
Please describe the changes in detail.

## Screenshots

Please include screenshots, gifs, etc.

## Tests
I ran `npm test` and all the tests are passed
Please describe how the change has been tested.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
could you drop a screenshot?

**Comment by anth-volk** [comment]
Or perhaps a brief screen recording demonstrating the successful navigation

**Comment by dotslashbit** [comment]
Screenshot 2023-12-22 at 2 23 56 AM

**Review by anth-volk — CHANGES_REQUESTED** [review]
To be clear, we're hoping to leave the Donate navbar alone, but on the existing Donate page, change the link on the button that says "SUPPORT TRANSPARENT POLICY ACCESS".

**Comment by dotslashbit** [comment]
it says file size is too big when sending the video, is there any other wawy to send the video to you?

**Comment by anth-volk** [comment]
We actually do want to maintain our own Donate page, it's just the button on the Donate page we're hoping to change

**Comment by anth-volk** [comment]
Ah, that’s okay, looks like the change wasn’t quite correct anyway

**Comment by dotslashbit** [comment]
> To be clear, we're hoping to leave the Donate navbar alone, but on the existing Donate page, change the link on the button that says "SUPPORT TRANSPARENT POLICY ACCESS".

Okay, let me do that and get back to you

**Comment by MaxGhenis** [comment]
you can use a tool like loom to drop a link to a screen recording

**Comment by dotslashbit** [comment]
I have made the required changes, here's the loom link https://www.loom.com/share/df6dc346b882416e9c0a981af65e1a55?sid=961e8948-8e13-4eec-b355-28aff07661d5

**Comment by MaxGhenis** [comment]
Please leave the menu button as-is and just change the teal button on the donate page

**Comment by anth-volk** [comment]
Thanks for removing the changes to the Donate tab and adding the new link, @dotslashbit! We appreciate the change.

**Review by anth-volk — APPROVED** [review]

**Comment by MaxGhenis** [comment]
@anth-volk note the video shows the changes still affect the tab

**Comment by anth-volk** [comment]
@MaxGhenis If you're referring to the Loom video, I'm not seeing the changes myself. That said, I'll wait to merge.

**Comment by dotslashbit** [comment]
I hope now my PR can be merged

**Comment by anth-volk** [comment]
@dotslashbit As you can imagine, editing prod is a sensitive thing, so I'll await Max's commentary, but don't worry, your work will be incorporated

**Comment by dotslashbit** [comment]
Thanks for this opportunity, I hope I can contribute to this repo more

**Comment by MaxGhenis** [comment]
Sorry, I think the mouse just moved quickly from the tab to the button so I misinterpreted the change. Good to go, thanks!

**Pull request merged**
