### PR TITLE
updated a element color

### LINKED ISSUE #1246: Within the calculator portions of the app, links are often displayed as standard text
For example, on the `Reproduce in Python` page shown in the image below, the text "Python notebook" is actually a link, but it's not displayed as such. This should definitely be obvious, and my theory would be that we should either use the browser's standard highlighting (which isn't far off from our color scheme, anyway) or define a clear theme to handle this.

Screen Shot 2024-01-22 at 2 31 35 PM

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes #1246 
Updated the link presentation in reproduce python section

## Screenshots

Screenshot 2024-01-23 at 5 27 48 AM

### CODE REVIEW

**Review by MaxGhenis — APPROVED** [review]
Thanks could you just change `into` to `in` on line 48?

**Review by anth-volk — CHANGES_REQUESTED** [review]
Actually, before we push this, can you also show this link in the blue color that we use for the navbar? I'm thinking this teal is pretty painful on the eyes.

**Comment by anth-volk** [comment]
Also, what tool do you use to capture screenshots? It seems pretty neat.

**Comment by dotslashbit** [comment]
Screenshot 2024-01-24 at 12 25 14 AM

**Comment by dotslashbit** [comment]
> Also, what tool do you use to capture screenshots? It seems pretty neat.

I use built-in screenshot feature of mac

**Review by anth-volk — APPROVED** [review]
Thanks @dotslashbit! This looks great.

**Pull request merged**
