### PR TITLE
Add year in chart titles

### LINKED ISSUE #1243: State year in chart titles
All charts omit the year from the title, e.g. [this](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=46315&region=enhanced_us&timePeriod=2025&baseline=2)
image

The labor supply one says "this year", regardless of the year
image

Let's add `in {year}` to the end of each chart title

### PR DESCRIPTION
**Pull request by czhou578**
## Description
Fixes #1243

## Changes

Added the year that is chosen by the user to the end of all the chart titles. 

## Screenshots
image
image

## Tests

None have been added

### CODE REVIEW

**Comment by anth-volk** [comment]
Also, just as advice, in the future, you may consider following a slightly different flow when opening PRs:

1. Fork the repo that you want to contribute to
2. Keep branch master or main in sync with the original repo by pulling the original repo's code at times; typically (if the original repo is called "upstream" by Git) this means running git pull upstream master, then git push origin master to sync the code to your local repo
3. Create branches on your fork off of your master or main branch. Periodically, if you're working on something for a while, you might also run git rebase master within your feature branch to sync your code with any new changes.
4. When you're done with the feature or bug fix, open the PR from your branch to the live main or master.

This just ensures that we don't run into merge conflicts down the road, especially if you contribute for a longer period.

Thanks so much!

**Comment by czhou578** [comment]
The YAML file called query_issues should be deleted already. Thanks for the advice; I will adhere to it as closely as possible in the future.

**Comment by MaxGhenis** [comment]
Just to add to @anth-volk's advice, I'd suggest using the GitHub VS Code extension and its ["Start working on issue" feature](https://code.visualstudio.com/blogs/2020/05/06/github-issues-integration#_working-on-issues). This automatically assigns you to the issue, creates a new branch, and prepopulates the commit message with a note about the issue number.

**Comment by czhou578** [comment]
Oh wow, I never knew about this at all. Thanks @MaxGhenis!

**Comment by anth-volk** [comment]
@czhou578 Perfect, will review a bit later today, then.

**Pull request merged**
