### PR TITLE
Move png and csv download buttons from the left pane to the middle pane.

### LINKED ISSUE #759: Chart `Download` button/dropdown is in the left pane
Instead of by the chart
image

### PR DESCRIPTION
**Pull request by abhcs**
## Description

Fixes #759 by moving the download png and csv actions next to the actions for sharing results and moving this new group of actions below the chart.

## Method for fix

* I have created a new component ResultActions that shows download or share results actions to the user.
  * This component accepts functions for downloading files and links for sharing the results as input.
  * This component shows buttons (from antd) to show the download and sharing actions.
  * The buttons contain icons from ant-design; the old icons were not modified but new icons were added for the download actions.
  * Previously the icons were wrapped in `<a>` tags but I have used buttons and informative tooltips since we have removed the "Share this result" text.
* I have used ResultActions component in the PolicyOutput and HouseholdOutput components.
  * I have moved the download png and csv functions from the DownloadCsvButton component to the PolicyOutput component.
  * I have used the useImperativeHandle React hook to access the 'create csv data' logic residing in each chart (this complexity cannot be avoided without moving the logic outside the components, which is a big change).
  * I have deleted the DownloadCsvButton component since it was no longer being used.

## Tests

I have checked that the buttons are functioning as expected for most chart types.

### Summary
📝🎨♻️

This pull request refactors the output components of PolicyEngine to use a new `ResultActions` component for downloading and sharing the results. It also simplifies the code by removing redundant props and components, and by using `React.forwardRef` and `useImperativeHandle` to access custom methods. It also improves the readability and consistency of the variable names and the component identification. Additionally, it adds a comment to the `ResultActions` component and a style property to the `ResultsPanel` component.

> _We are the masters of the output charts_
> _We use the `ResultActions` to share our art_
> _We refactor and simplify with `React.forwardRef`_
> _We unleash the power of the `useImperativeHandle`_

### Walkthrough
*  Add `ResultActions` component to enable download and share functionality for output charts ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-e24d988aceeedd9e7390c0031d192d4b2cb1ae84aa77670f7460b38b74c904d1R1-R88), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL29-R37), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL664-R648))
*  Remove unused imports and components related to download and share functionality from output components ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-ec040841afa1a198c029f240d07eb3e001304de021910e91356cc6eaafc12909L12-R14), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-ec16d5261d93e698e4741e7df864ae2f82625d02047ca9697db51ae269ee05a2L161-R168), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-ec16d5261d93e698e4741e7df864ae2f82625d02047ca9697db51ae269ee05a2L188-L197), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-f561e2313f626b35f5ba151c460ff2c4a2919ef88e0a5ba86fd61f60a0ac4b8aL162-R167), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-f561e2313f626b35f5ba151c460ff2c4a2919ef88e0a5ba86fd61f60a0ac4b8aL187-L196), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-af88a6bb0672282e83959a0a8317e5259f5e148af72f4901f431073ca751e7b3L214-R220), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-af88a6bb0672282e83959a0a8317e5259f5e148af72f4901f431073ca751e7b3L241-R241), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3L25-R30), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3L254-L278), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3L287-L296), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8L215-R224), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8L236-L246), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cL227-R234), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cL248-L258), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d50bb4f3433b375516906846f34ac9a1d86d9d361680f9d47cf9cf58f4a44cf5L199-R205), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L291-R293), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L312-L321), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-71b88b3f4ac09980a01bd897cb30749591d957adfb78c6de0b91e8010b71072aL508-R512), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-71b88b3f4ac09980a01bd897cb30749591d957adfb78c6de0b91e8010b71072aL526-L535), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d41e88c8038a48564a3b9efe556677354d37e1fc69a77bd612f33d5aa98cda85L492-R494), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d41e88c8038a48564a3b9efe556677354d37e1fc69a77bd612f33d5aa98cda85L510-L519), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL21-L22), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL104-L108), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL505-R566), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL628-L656), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33L210-R219), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33L231-L240), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fL227-R236), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fL248-L257), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbL255-R262), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbL276-L285), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2b5717cbee57bbbc685fbb5310eb4f84ee1f0b60fc6215373dd876f733f47fb4L167-R170), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2b5717cbee57bbbc685fbb5310eb4f84ee1f0b60fc6215373dd876f733f47fb4L189-L198), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL167-R169), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL189-L198), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-53e00af386370e2583bc217d2dc3a9b8192fbc7396679cb55663ecfd7d21c56e))
*  Wrap output components with `React.forwardRef` and use `useImperativeHandle` hook to expose custom methods for generating csv data ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-ec16d5261d93e698e4741e7df864ae2f82625d02047ca9697db51ae269ee05a2L1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-ec16d5261d93e698e4741e7df864ae2f82625d02047ca9697db51ae269ee05a2L10-R14), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-ec16d5261d93e698e4741e7df864ae2f82625d02047ca9697db51ae269ee05a2L205-R196), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-f561e2313f626b35f5ba151c460ff2c4a2919ef88e0a5ba86fd61f60a0ac4b8aL1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-f561e2313f626b35f5ba151c460ff2c4a2919ef88e0a5ba86fd61f60a0ac4b8aL10-R13), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-f561e2313f626b35f5ba151c460ff2c4a2919ef88e0a5ba86fd61f60a0ac4b8aL204-R195), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-af88a6bb0672282e83959a0a8317e5259f5e148af72f4901f431073ca751e7b3L1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-af88a6bb0672282e83959a0a8317e5259f5e148af72f4901f431073ca751e7b3L9-R12), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3L1-R7), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3L14-R22), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3R71-R97), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8L1-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8L9-R18), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cL1-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cL9-R18), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d50bb4f3433b375516906846f34ac9a1d86d9d361680f9d47cf9cf58f4a44cf5L1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d50bb4f3433b375516906846f34ac9a1d86d9d361680f9d47cf9cf58f4a44cf5L9-R13), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L9-R12), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-71b88b3f4ac09980a01bd897cb30749591d957adfb78c6de0b91e8010b71072aL1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-71b88b3f4ac09980a01bd897cb30749591d957adfb78c6de0b91e8010b71072aL10-R13), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d41e88c8038a48564a3b9efe556677354d37e1fc69a77bd612f33d5aa98cda85L1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d41e88c8038a48564a3b9efe556677354d37e1fc69a77bd612f33d5aa98cda85L10-R13), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33L1-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33L9-R18), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fL1-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fL9-R18), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbL1-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbL9-R18), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2b5717cbee57bbbc685fbb5310eb4f84ee1f0b60fc6215373dd876f733f47fb4L1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2b5717cbee57bbbc685fbb5310eb4f84ee1f0b60fc6215373dd876f733f47fb4L10-R14), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL1-R1), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL10-R13))
*  Pass `childRef` prop to output components to access their custom methods from `PolicyOutput` component ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL319-R314), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL344-R338), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL354-R348), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL364-R358), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL374-R368), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL384-R378), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL395-R389), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL407-R401), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL419-R413), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL431-R425), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL443-R437), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL454-R448), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL464-R458), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL474-R468), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL484-R478), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bR487))
*  Rename `data` variable to `csvData` in output components to clarify its purpose ( [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8L204-R207), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cL212-R215), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d50bb4f3433b375516906846f34ac9a1d86d9d361680f9d47cf9cf58f4a44cf5L169-R183), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L282-R280), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33L201-R204), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fL212-R215), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbL240-R243), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2b5717cbee57bbbc685fbb5310eb4f84ee1f0b60fc6215373dd876f733f47fb4L159-R158), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL159-R157))
*  Add `displayName` property to output components for debugging purposes ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2a9a57cb3f930da94ecfd413c52afa6957eb4d07b639ab31d7bb11cc96f9f4c3L305-R305), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-06f27d7309a6d91cb25d3d1414889381cdcdc8a7800d0a909a4a917fc8ffc2a8L253-R249), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-542532ce614925fa12fb518ca5e9c503284edc9d0393b803294609058b3cd11cL265-R260), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L328-R319), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-71b88b3f4ac09980a01bd897cb30749591d957adfb78c6de0b91e8010b71072aL544-R536), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-d41e88c8038a48564a3b9efe556677354d37e1fc69a77bd612f33d5aa98cda85L528-R519), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-477c61d506ee800a649da9f71364082f7d98c738c04b51a436633f2efef13e33L247-R244), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-04e2d157bf184eb210182f434c2f34a470a711a29e5aa61e626d0cabb949526fL264-R261), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-666b4a2954e170f5d63c511ffebea4d88b6f3ef1c2d7e836d4cfc6b6fe268bcbL292-R288), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-2b5717cbee57bbbc685fbb5310eb4f84ee1f0b60fc6215373dd876f733f47fb4L206-R198), [link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL206-R197))
*  Add `overflow: auto` style property to `ResultsPanel` component to enable scrolling ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-81eca4ebc9235127e803c4dfa8d48afb99b24d5c7a75051db308bfdf9cc22fd1R15))
*  Move `RelativeImpactByWealthDecile` component from `src/pages/policy/output/RelativeImpactByWealthDecile.jsx` to `src/layout/ResultActions.jsx` and wrap it with `React.memo` ([link](https://github.com/PolicyEngine/policyengine-app/pull/846/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL206-R197))

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Thanks- though just testing locally I seem to be getting a white screen on the charts loading? Here's the error:

image

**Review by nikhilwoodruff — CHANGES_REQUESTED** [review]
.

**Review by anth-volk — CHANGES_REQUESTED** [review]
Hey @abhcs, thanks for your submissions on this issue, the way we have it now certainly creates a strange UX.

I understand what you're shooting for with your edits. That said, positioning the bar as you have and changing the color of the icons would conflict with the household calculator pages, which contain the same components. To proceed, could you do the following:

1. Move the bar back to the top (it may be better at the bottom, but I think that should be opened as a separate issue to maintain proper scoping)
2. ~~Return the icons to what they were before, sitting inside the table that they do~~
3. ~~Maintain the "Share this result" text that was there before~~

Otherwise, I appreciate your React logic, as well as the use of the new useImperativeHandle hook. Thanks so much!

Edit: My apologies, on reading the discussion on #759, please ignore numbers 2 and 3. Even so, I think it'd be preferable to return the icons to their previous colors and alignment.

**Comment by abhcs** [comment]
@anth-volk The changes extend to the household pages:

Screenshot 2023-12-12 at 12 58 20 PM

I am happy to make changes to colors, alignment, tooltip text, etc. None of my PRs are meant to be perfect, but only a step in the right direction. I thought that the blue colors were kinda odd but they were provided by ant-design by default for link buttons. We can have a different color for link buttons, or even use black. The different colors may help the user to differentiate between actions that take them out of the website (link actions) vs actions that are local (download, copy link).

**Comment by anth-volk** [comment]
My apologies, you're right, they do extend to the household calculator. With regard to the color, I think you're right, they could be a benefit, but I think they should be changed as part of a separate issue and PR if we are to go that way. I think it's best to keep each PR scoped to resolving the particular issue logged.

**Comment by anth-volk** [comment]
@MaxGhenis or @nikhilwoodruff This commit removes the borders around the buttons for the download and share actions - how set are we on maintaining said borders?

@abhcs Love the use of forwardRef. Once I've confirmed on the borders, I'll either ask you to add them back or approve and push.

**Comment by MaxGhenis** [comment]
could you drop a screenshot of the buttons?

**Comment by anth-volk** [comment]
Screen Shot 2023-12-21 at 2 38 06 PM

**Comment by abhcs** [comment]
Due to the use of `forwardRef` users may encounter the error Nikhil reported above if they are in the middle of a workflow, e.g., working on a policy. They can fix it by restarting their process from Home.

**Comment by MaxGhenis** [comment]
removing borders sgtm

**Comment by anth-volk** [comment]
@abhcs Certainly, forwarding refs isn't ideal, but it is nice to see the use of advanced features to solve challenges. That said, can you describe why you went down that pathway? I'm wondering if there isn't a different method of successfully building this, since the original didn't do so.

**Comment by abhcs** [comment]
My original logic for using the escape hatch is given in the PR description: 'I have used the `useImperativeHandle` React hook to access the 'create csv data' logic residing in each chart (this complexity cannot be avoided without moving the logic outside the components, which is a big change).'

Pick `AverageImpactByDecile`, for instance. The csv data object (called `data`) is created inside the component, and I needed some way to access it without changing the files too much. Hence, `useImperativeHandle`.

However, if you look at `AverageImpactByDecile` more closely, you can see that the `data` is created from `impact`, which is available to `PolicyOutput`. Therefore, you may be able to create the csv data object for the average impact by decile chart type without accessing the state inside the `AverageImpactByDecile` chart component. This could, in theory, avoid `useImperativeHandle`. I have not checked whether this works for the dozen chart types affected by this PR.

**Comment by abhcs** [comment]
Since I have started thinking about this, let me see if I can get rid of `forwardRef`. I will let you know if it looks like too much work.

**Comment by anth-volk** [comment]
Thanks @abhcs, appreciate you giving a second think to this. Additionally, if you need to make more comprehensive changes to the components, please feel free, assuming it can be done workably.

**Comment by anth-volk** [comment]
Thanks so much @abhcs. Since this is a more significant fix, I'll give it a bit more attention early next week.

**Comment by abhcs** [comment]
Sounds good. I will also need to look at the changes with fresh eyes next week.

**Comment by abhcs** [comment]
I have opened a new PR (#1019) that refactors the policy output code significantly. I am still leaving this PR open for the time being because it doesn't change the code too much. However, at most one of the two PRs will eventually make it to mainline.

**Comment by anth-volk** [comment]
Closing because this was superseded by #1019.

**Pull request closed without merging**
