### PR TITLE
Adds social share icons

### LINKED ISSUE #224: Add social share interactives for blog posts
e.g. like in this FT article, on the left:

image

### PR DESCRIPTION
**Pull request by QianruZhang78**
Fixes #224

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks @QianruZhang78, could you drop a screenshot?

Also FYI I added `Fixes #224` to your description to link it to the issue.

**Comment by QianruZhang78** [comment]
@MaxGhenis Thanks Max. 
Screen Shot 2023-03-19 at 2 28 24 PM

This is how it looks like right now.

**Review by nikhilwoodruff — COMMENTED** [review]
Thanks for this so far @QianruZhang78 - the icons look nice and fit with the rest of the page. I was actually more thinking that they should also behave in a similar way to the FT example- i.e. if you click them, they pre-populate a post on the respective platform. Here's an example: when I click on the Twitter icon in [this FT story](https://www.ft.com/content/9fe40e6a-f01f-4205-b885-7771d305721e), it takes me to this Twitter page:
image

Looking at the URL it took me to, I think this is actually achievable here- we just need to add in the relevant query parameters in the URL:
> https://twitter.com/intent/tweet?url=https://www.ft.com/content/9fe40e6a-f01f-4205-b885-7771d305721e&text=UBS%20agrees%20%243.25bn%20rescue%20deal%20for%20rival%20Credit%20Suisse

Do you think you could add this? Thanks!

**Comment by QianruZhang78** [comment]
@nikhilwoodruff Thanks for your explanation! That definitely makes more sense, I'll start working on it now.

**Comment by QianruZhang78** [comment]
Screen Shot 2023-03-20 at 11 16 12 AM
I think I've got it to work. @nikhilwoodruff

**Comment by nikhilwoodruff** [comment]
Awesome, thanks! Sorry final nitpick, could we add the title to the query parameters as well, like the FT does?

**Comment by QianruZhang78** [comment]
Screen Shot 2023-03-22 at 12 09 56 AM
Sorry for the late response, I've added title to the query parameters:)

**Pull request merged**
