### PR TITLE
Fix #238: Reflect US state / UK region in chart title

### LINKED ISSUE #238: Reflect US state / UK region in chart title
For example, it'd be cool if [this chart for Iowa](https://policyengine.org/us/policy?reform=3826&focus=policyOutput.intraDecileImpact&region=ia&timePeriod=2023&baseline=2) had the title:
>Restoring the ARPA CTC would benefit 45% of Iowans

image

And then:
>Restoring the ARPA CTC would reduce Iowa's poverty rate by 2.9%

and so on

### PR DESCRIPTION
**Pull request by QianruZhang78**

### CODE REVIEW

**Comment by QianruZhang78** [comment]
All chart title updated, see pic:
Screen Shot 2023-04-10 at 1 48 49 AM
Screen Shot 2023-04-10 at 1 48 57 AM
Screen Shot 2023-04-10 at 1 49 06 AM
Screen Shot 2023-04-10 at 1 49 12 AM
Screen Shot 2023-04-10 at 1 49 17 AM
Screen Shot 2023-04-10 at 1 49 21 AM
Screen Shot 2023-04-10 at 1 49 25 AM
Screen Shot 2023-04-10 at 1 49 28 AM
Screen Shot 2023-04-10 at 1 49 33 AM
Screen Shot 2023-04-10 at 1 49 38 AM

**Comment by nikhilwoodruff** [comment]
Thanks @QianruZhang78 - does this definitely except the case of `uk`/`us`? e.g. we'd want to avoid 'in the UK'.

**Comment by QianruZhang78** [comment]
> Thanks @QianruZhang78 - does this definitely except the case of `uk`/`us`? e.g. we'd want to avoid 'in the UK'.

Nope I thought we want to include them, I'll add the exceptions.

**Comment by QianruZhang78** [comment]
@nikhilwoodruff I've added the exception cases in all features, this is an example of UK Outcomes by income decile chart:
Screen Shot 2023-04-10 at 10 54 29 PM
Screen Shot 2023-04-10 at 10 54 35 PM
And this is how it looks like for the US chart:
Screen Shot 2023-04-10 at 10 55 29 PM
Screen Shot 2023-04-10 at 10 55 35 PM

Please check:)

**Review by nikhilwoodruff — APPROVED** [review]
Looks great @QianruZhang78! Thanks

**Pull request merged**
