### PR TITLE
Updated on the Subscribe Button Link + COLORS

### PR DESCRIPTION
**Pull request by christinal59**
### Summary
📧📝🎨

This pull request introduces a new feature to the blog page: a subscription form for the newsletter. It also improves the readability of the `BlogPage.jsx` file by applying consistent formatting.

> _From the ashes of the blog, a new form rises_
> _`SubscribeForm` is the name of the beast_
> _It lures you in with promises of wisdom and surprises_
> _But beware, it may devour your email address at least_

### Walkthrough
*  Add a subscription form for users to sign up for Policy Engine's newsletter ([link](https://github.com/PolicyEngine/policyengine-app/pull/523/files?diff=unified&w=0#diff-d6e4e143ce03a0a160a303e0ec2ed8cc5459417da7c3478f7623ccab991baeb4R366-R459), [link](https://github.com/PolicyEngine/policyengine-app/pull/523/files?diff=unified&w=0#diff-d6e4e143ce03a0a160a303e0ec2ed8cc5459417da7c3478f7623ccab991baeb4R632-R636), [link](https://github.com/PolicyEngine/policyengine-app/pull/523/files?diff=unified&w=0#diff-d6e4e143ce03a0a160a303e0ec2ed8cc5459417da7c3478f7623ccab991baeb4R642))
* Improve formatting and spacing in `BlogPage.jsx` ([link](https://github.com/PolicyEngine/policyengine-app/pull/523/files?diff=unified&w=0#diff-d6e4e143ce03a0a160a303e0ec2ed8cc5459417da7c3478f7623ccab991baeb4L6-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/523/files?diff=unified&w=0#diff-d6e4e143ce03a0a160a303e0ec2ed8cc5459417da7c3478f7623ccab991baeb4R24-R25))

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thank you - could you please
* Remove the issue number from the title
* Edit the first PR comment to include "Fixes #476" - this will connect the PR to the issue so merging it will close the issue
* Add a screenshot

**Review by nikhilwoodruff — COMMENTED** [review]
Looks nice, thanks for the styling changes @christinal59! Tried it out locally; just a few minor tweaks and then I think we can merge this:
- [ ] Could we make the box as wide as the blog text content so it lines up?
- [ ] Could we round the edges of the `Subscribe` button like other buttons?
- [ ] When I tried clicking subscribe I got the below opened in a new tab, I get the below. The UBI Center's one works (also below). Do you know why this is? Let me know if not or if you need more info from our side on the mailchimp setup. We did use to have a working subscribe button on the homepage which we can dig out from the repo history if that's helpful.

## PolicyEngine result

image

## UBI Center result

image

**Comment by nikhilwoodruff** [comment]
Oh actually I've just looked at the .jsx file linked in the original issue: I think we need to use the `<form>` setup in that example. LMK if you need a hand with that!

**Comment by christinal59** [comment]
@nikhilwoodruff I might need a hand with the <form> setup. Thank you!

**Comment by christinal59** [comment]
hi @nikhilwoodruff  I made the update on Subscribe Form so now the box is as wide as the blog text content!! Please take a look when you got the time! 
Screen Shot 2023-05-07 at 11 42 12 PM

**Review by nikhilwoodruff — APPROVED** [review]
Looks great, thanks @christinal59! I made a minor formatting change (centered the subscribe button) and I think we can merge this. Thanks for your contribution!

**Comment by christinal59** [comment]
Hi @nikhilwoodruff noted, thank you!!

**Pull request merged**
