### PR TITLE
Update wording of "average" for average impact by docile and relative…

### PR DESCRIPTION
**Pull request by yellohCrayon**
… impact by wealth docile

### Summary
📝🚚♻️

This pull request refactors the code for the output charts of the policy simulation, moving the relative impact by wealth decile chart to the same file as the average impact by decile chart. It also improves the readability of the chart headings by changing the wording and spacing.

> _`Decile` charts merge_
> _Wording and spacing improve_
> _Winter of refact'ring_

### Walkthrough
*  Refactor and improve the wording and spacing of the charts for average and relative impact by decile ([link](https://github.com/PolicyEngine/policyengine-app/pull/552/files?diff=unified&w=0#diff-ec16d5261d93e698e4741e7df864ae2f82625d02047ca9697db51ae269ee05a2L128-R135), [link](https://github.com/PolicyEngine/policyengine-app/pull/552/files?diff=unified&w=0#diff-3479abe14967df8c0649d35cc8a385878b52956281431d871039601f975a133cL126-R129))

I was looking around and saw this type of wording happens in two other places. I could only replicate the two in the screen shot and  RelativeImpactByDecile was done in prev PR https://github.com/PolicyEngine/policyengine-app/pull/551
Screenshot 2023-05-24 at 10 36 56 PM

### CODE REVIEW

**Comment by MaxGhenis** [comment]
This would also be in AverageImpactByWealthDecile right?

**Comment by yellohCrayon** [comment]
> This would also be in AverageImpactByWealthDecile right?

Yup @MaxGhenis this PR changes it in AverageImpactByDecile and AverageImpactByWealthDecile but I don't know how to see the AverageImpactByWealthDecile chart do you know the steps to see it?

**Comment by MaxGhenis** [comment]
Wealth deciles are only in the UK model. You can change country on the homepage via the flag in the upper right.

**Comment by yellohCrayon** [comment]
Screenshot 2023-05-30 at 7 00 52 PM
Screenshot 2023-05-30 at 7 01 00 PM
Screenshot 2023-05-30 at 7 03 03 PM
Screenshot 2023-05-30 at 7 02 21 PM

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Thanks! Also appreciate the modularization.

**Pull request merged**
