### PR TITLE
add a single command for handling both code linting and formatting.

### LINKED ISSUE #865: Add a command to handle both linting and formatting with Prettier
When running `npm run lint`, it prompts me to execute Prettier separately for formatting. It would be convenient if `npm run lint` could handle both linting and formatting without the need for an additional Prettier command.

Screenshot 2023-11-22 at 6 11 27 PM

### PR DESCRIPTION
**Pull request by avelynhc**
fixes #865
- `npm run lint` now can handle both linting and formatting without the need for an additional Prettier command.
- includes previous [pr-863](https://github.com/PolicyEngine/policyengine-app/pull/863)

### CODE REVIEW

**Review by anth-volk — COMMENTED** [review]
I would want Max's thinking on the changes to HouseholdPage before feeling comfortable "signing off," so to speak. The reason `fips` fails is because it was a variable that every household had and its default value was 6. The variable was removed around Oct. 31, but because it had a truthy value, the code we used to update households should prompt every household created prior to Oct. 31-ish to re-create their household. It doesn't at the moment because issue #762 breaks the interstitial that's supposed to appear, making everything look okay. #762 should be resolved with PR #867. The front-end test fails at the moment because it pulls a real household for testing purposes, and since every US household had `fips`, it fails.

So here's what I'm thinking. We could merge this code, which will prevent household invalidation across the board and will make the test pass, but is a bit of an ugly workaround because we'll have to do it any time a variable like `fips` is deleted in the future. We could re-engineer the household object the test uses to make it hardier, but that will still invalidate all households. And/or, moving forward, we could have a discussion about how better to treat deleted truthy variables in this particular component.

Curious to hear @MaxGhenis's thoughts on this.

**Comment by MaxGhenis** [comment]
Also would suggest scoping PRs to more specific issues, e.g. as we're discussing the lint/format change in #902

**Comment by anth-volk** [comment]
@MaxGhenis Fair points on both

**Review by anth-volk — COMMENTED** [review]
This was already solved and implemented via #902.

**Pull request closed without merging**
