### PR TITLE
refactor: Donate.jsx

### PR DESCRIPTION
**Pull request by amar9312**
New PR for issue [776](https://github.com/PolicyEngine/policyengine-app/issues/776)

changes: 
* remove onClick handler from `<ActionButton>`
* Wrap `<ActionButton>` in `<Link>`

npm test:
No tests found related to files changed since last commit.

### CODE REVIEW

**Comment by anth-volk** [comment]
If you wouldn't mind holding off on this, I have an open PR (https://github.com/PolicyEngine/policyengine-app/pull/867) that more fundamentally re-engineers buttons and would likely conflict with this change

**Comment by anth-volk** [comment]
In fact, if you wouldn't mind waiting, then perhaps adding precisely this functionality to the new LinkButton component added in #867, that could enhance functionality app-wide

**Comment by amar9312** [comment]
> If you wouldn't mind holding off on this, I have an open PR (#867) that more fundamentally re-engineers buttons and would likely conflict with this change

That's fine, no problem.

**Comment by anth-volk** [comment]
Hey @amar9312, thanks for holding off. Would you be willing to restart this issue? The button components have been refactored, but this remains an issue.

**Comment by amar9312** [comment]
> Hey @amar9312, thanks for holding off. Would you be willing to restart this issue? The button components have been refactored, but this remains an issue.

@anth-volk Sure sir, I can do it by EOD Tuesday. Do you want me to do a new PR?

**Comment by anth-volk** [comment]
> > Hey @amar9312, thanks for holding off. Would you be willing to restart this issue? The button components have been refactored, but this remains an issue.
> 
> @anth-volk Sure sir, I can do it by EOD Tuesday. Do you want me to do a new PR?

I think it may be preferable to avoid a bunch of merge conflicts, if you'd be willing to do so

**Pull request closed without merging**
