### PR TITLE
Navbar resizing

### LINKED ISSUE #893: Alter navbar height to use min-width on mobile displays to add support for smaller screens
Because the mobile navbar height is set at 90px, on small screens, it takes up a significant amount of real estate. Might be good to set it as min-width(90px, some vh value) and scale the buttons and logo accordingly.

### PR DESCRIPTION
**Pull request by maurobusso**
### Summary
📱🎨🔄

Redesigned the header component to improve the user interface for mobile devices. Adjusted the spacing constants and props to align with the new header design. Modified `src/redesign/components/Header.jsx` and `src/redesign/style/spacing.jsx`.

> _Sing, O Muse, of the skillful coder who redesigned the header_
> _To fit the screens of mobile devices, those swift-winged messengers_
> _He gave it height conditional, and a menu button custom-made_
> _And shrunk the logo and the calculator, like the sun and moon in eclipse_

### Walkthrough
*  Adjust header height and layout for mobile devices ([link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL20-R22), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL38-R42), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL90-R94), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL106-R111), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL121-R126), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bR171-R208), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-a658b8a5d45f38a053c22156fe0484f84483fa299db3316fb53c0ff079a4fd3cR4), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-a658b8a5d45f38a053c22156fe0484f84483fa299db3316fb53c0ff079a4fd3cR33))
* Rename `direction` prop of `HoverBox` component to `hoverStart` to avoid confusion with `motion.div` prop ([link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL173-R215), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL257-R299), [link](https://github.com/PolicyEngine/policyengine-app/pull/918/files?diff=unified&w=0#diff-1487a7d7ccfc0c177b386c9a43d4c38a893dd2017a8489aa072d16488ccb098bL316-R358))

Fix #893 

I had a go and try to improve the navbar on mobile screen,
Let me know what you think.

### CODE REVIEW

**Review by anth-volk — COMMENTED** [review]
Thanks for your contribution! Since the MobileHamburger component is functionally just about the exact same functionally and stylistically as the Hamburger component, I feel it would be preferable to instead add conditional sizing into the main `div`'s height, width, and any other relevant style parameters, using the new constants that you created as the values there. 

I'd say that preliminarily, since I also haven't yet viewed it.

**Review by anth-volk — COMMENTED** [review]
This all looks great to me! I'm going to defer to @nikhilwoodruff for his final sign-off.

**Comment by maurobusso** [comment]
Okay thanks, I am new to Open Source so fell free to let me know if i am doing something wrong :)

**Review by nikhilwoodruff — APPROVED** [review]
Looks ok to me on mobile viewports- thanks very much @maurobusso!

**Pull request merged**
