### PR TITLE
fix twitter-embed component with existing package react-twitter-embed

### LINKED ISSUE #925: Footer's Twitter timeline element doesn't display
Sometimes it's completely absent, other times it's a 1px-width white bar

### PR DESCRIPTION
**Pull request by orestisathanasopoulos**
### Summary
🧹🐦⚛️

Updated footer component to use React library for Twitter timeline. This improves code quality and consistency in `src/redesign/components/Footer.jsx`.

> _`Footer` component_
> _Embeds Twitter with React_
> _Winter of clean code_

### Walkthrough
*  Embed a Twitter timeline in the footer using the `TwitterTimelineEmbed` component ([link](https://github.com/PolicyEngine/policyengine-app/pull/957/files?diff=unified&w=0#diff-ec170e9bc78120aa523c0ba45045d2b17fb72c7b48b0f45b7711c1e4259be387R6),[link](https://github.com/PolicyEngine/policyengine-app/pull/957/files?diff=unified&w=0#diff-ec170e9bc78120aa523c0ba45045d2b17fb72c7b48b0f45b7711c1e4259be387L57-R66))

resolve #925 

I used an existing package ("react-twitter-embed") to fix the twitter timeline footer issue. Please note that currently Twitter seems to allow only verified/premium (blue checkmark) accounts to embed their timelines.

### CODE REVIEW

**Comment by anth-volk** [comment]
You're right, even the official tweet embedding formatter (https://publish.twitter.com/?query=%40ThePolicyEngine&widget=Timeline) just shows the PolicyEngine account as having no posts. @MaxGhenis and @nikhilwoodruff how would you like to proceed with this? I've yet to find a workaround on this.

**Comment by MaxGhenis** [comment]
that link now shows posts https://publish.twitter.com/?query=%40ThePolicyEngine&widget=Timeline

image

**Comment by anth-volk** [comment]
This is what I get when I navigate there:

Screen Shot 2023-12-21 at 6 09 38 PM

I have to wonder why

**Comment by MaxGhenis** [comment]
Are you signed in to some Twitter account?

**Comment by anth-volk** [comment]
I’m not, as I don’t have one. I had assumed these feeds worked like pre-Musk Twitter, where they were basically publicly visible, but I suppose that’s not the case.

**Comment by orestisathanasopoulos** [comment]
There's an issue with Twitter's API (see this long [discussion thread](https://twittercommunity.com/t/again-list-widget-says-nothing-to-see-here-yet-if-logged-out/198782)).

Many posters mention this [third-party solution](https://www.athabasca.dev/twitterwidget) but it is not a real fix and it is obviously dependent on the third-party's existence/goodwill.

**Comment by anth-volk** [comment]
What a mess. I'll probably take some time today to play around with this and see what I can find.

**Comment by anth-volk** [comment]
I think it’s pretty important to display the feed for users who aren’t logged in; if it instead said something about “you’re not logged in,” that’d be one thing, but the Twitter timeline makes it look like we have no tweets. I think it’d be best to identify a third-party option and use that until (God forbid) it breaks. Seems like the one by Athabasca dev may work. I’ll investigate some more today.

**Comment by anth-volk** [comment]
As an update on this, I've been trying to get athabasca.dev's component to work, but theirs embeds a script in vanilla JS to render an anchor as an iframe, and React is not playing well with that. I spoke with their dev team and they offered to just send the iframe link, but unfortunately it appears that link wasn't permanent, as it eventually was replaced with a different feed. I'll keep trying a bit with this, but not sure how far I can get on it.

**Comment by anth-volk** [comment]
I would've preferred to just edit your PR, but I think I found a workaround using an iframe rendered by Athabasca Dev. I'm going to open a separate PR and ask for review from the team and also link you over there, @orestisathanasopoulos.

**Comment by orestisathanasopoulos** [comment]
No worries! Glad you managed to figure out a workaround :)

**Pull request closed without merging**
