### PR TITLE
Changes in the position of Line

### PR DESCRIPTION
**Pull request by psankhe28**
## Description
#1690 

## Changes

Moved the "Run the code below" line from the Reproduce in Python pages so that it sits above the code editor 

## Screenshots

image

## Tests

17/17 passed

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this @psankhe28. While it does look good, could you also just lower the bottom padding on the line so that it matches the amount below "Include earning variation"? Otherwise, I think it'll be good to go after that.

**Comment by psankhe28** [comment]
image

New change

**Comment by anth-volk** [comment]
Thanks, this looks good! I'll check it out today or tomorrow.

**Review by anth-volk — APPROVED** [review]
Thanks for this @psankhe28! This all looks great.

**Pull request merged**
