### PR TITLE
Ant migration from v4 to v5

### LINKED ISSUE #1479: Upgrade to antd v5
This will require quite a few things to be done, as laid out at https://ant.design/docs/react/migration-v5. After this, dependabot PR can be merged.

### PR DESCRIPTION
**Pull request by czhou578**
## Description

Fixes #1479 

## Changes

Updated package.json and index.js to include the stylesheets for Ant Design v5. Changed the styling of tooltips, centered the modal content, and squared off input boxes.

## Screenshots

image
image
image

## Tests

No tests added.

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks so much for this, @czhou578. Could you also square off the modal edges?

**Comment by czhou578** [comment]
Done.

**Comment by anth-volk** [comment]
Thanks! Will review first-thing tomorrow.

**Comment by anth-volk** [comment]
I take that back, unfortunately I'll review this last-thing today haha. Toward the end of the day I'll have an update for you.

**Review by anth-volk — CHANGES_REQUESTED** [review]
Your work has been great on this, @czhou578. I just have a few last things, with no. 2 and 3 in the video below the list:

1. If possible, could you drop the commit where you change the color on the `Switch` (or just change it back)?
2. For some reason, this update completely destroys our date selector component, creating really strange behavior (you have to see it in the video to believe it). Would you be willing to look into why?
3. Could you square off the boxes in the household calculator? I think they're a separate entry type, which is why they're rounded. It should be on the pages in the `/src/household/input` folder

https://github.com/PolicyEngine/policyengine-app/assets/14987227/968fd4c8-4965-4f78-919d-d14cf79d8ce5

Thanks again for all of this, and feel free to reach out here or via Slack for questions, comments, etc.

**Comment by czhou578** [comment]
Hi @anth-volk, thanks for the feedback!

Just to confirm, you want me to square off the following in the household calculator?
image
image

Also, I did some research into why the dates were not correct in the range picker, and it turns out that Ant Design is no longer using the "moment" library for v5 (https://medium.com/ant-design/ant-design-5-0-is-released-27b2552f14a3). They have completely switched over to using the Day.js library. If we want to continue using the moment library, we have to configure webpack to support it, but I don't think we are using webpack. Completely transitioning to Day.js would be a lot more involved. Let me know what your thoughts are on this.

**Comment by czhou578** [comment]
Ok. I guess I'll do the checkbox issue then.

**Comment by anth-volk** [comment]
Thanks @czhou578, and sorry for the complications.

**Comment by anth-volk** [comment]
Closed in light of #1670.

**Pull request closed without merging**
