### PR TITLE
Added Linting Rule

### PR DESCRIPTION
**Pull request by psankhe28**
## Description
#1665 

## Changes

The no-console linting rule in ESLint discourages or prevents the use of console.log statements in your JavaScript codebase while allowing the use of other console methods like console.error, console.warn, console.info, and console.table.

## Screenshots
I have tested it on a file called test.js and test1.js.
image
image

Output:
image

## Tests

17/17 passed

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this contribution @psankhe28. Before I review, I just want to make sure - does this PR also remove garbage `console.log` statements and convert relevant ones to `console.debug`, `console.error`, etc.?

**Comment by psankhe28** [comment]
> Thanks for this contribution @psankhe28. Before I review, I just want to make sure - does this PR also remove garbage `console.log` statements and convert relevant ones to `console.debug`, `console.error`, etc.?

It removes all console.log and allows console.debug, error etc.

**Comment by anth-volk** [comment]
I'm not sure you understood my question. In at least 8 files (they're actually highlighted by GitHub in the "Files changed" tab), there are still `console.log` statements that will be errors if we merge this code. This issue asks contributors to remove garbage statements (e.g., on line 14 in `src/layout/Screenshottable.jsx`) and to transfer relevant ones (e.g., line 69 in `src/api/parameters.js`) to either `console.error` or `console.debug`.

**Comment by anth-volk** [comment]
That's alright. The approach you took was good - we are looking to do what you did - just to also modify those existing statements.

**Review by anth-volk — APPROVED** [review]
Thanks for your work on this a while back @psankhe28. We've done a bit more on top of the foundation you built and removed some code from a different fix that I believe may have been added to the local `master` branch. This should now be good to go.

**Pull request merged**
