### PR TITLE
fix: capitalise 'API' title on documentation page #1042

### PR DESCRIPTION
**Pull request by Ali-Aldawoodi**
## Description

Please provide a summary of the changes and which issue is fixed. Please include relevant motivation and context.
Capitalized 'api' on documentation page as it was more befitting. 
## Changes

Please describe the changes in detail.
Added a useEffect hook onto APIDocumentationPage.jsx in order to update title of page. 
## Screenshots

Please include screenshots, gifs, etc.
image

## Tests

Please describe how the change has been tested.
Change was tested locally.

### CODE REVIEW

**Comment by anth-volk** [comment]
Hi @Ali-Aldawoodi, thanks so much for your contribution! Before I check this out, could you run `make format` locally, then push again? We've started enforcing linting more strictly.

**Comment by Ali-Aldawoodi** [comment]
Yes of course! I am away from my computer right now so will do later this afternoon.

**Comment by anth-volk** [comment]
Sounds great, looking forward to it

**Comment by MaxGhenis** [comment]
Please also link the issue https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by Ali-Aldawoodi** [comment]
I am currently trying to run 'make format' in the terminal and am getting 'unknown command'. Would it otherwise be 'npm run fix' ? As I see that in the Makefile, under format.

**Comment by anth-volk** [comment]
First, let me ask: after forking the repository and opening it, did you run `make install` to install the packages necessary to run it?

If not, could you copy and paste your terminal output as a comment?

**Comment by Ali-Aldawoodi** [comment]
Yes of course. I was still able to make lint work via npm. And yes this is my terminal output.

image

**Comment by anth-volk** [comment]
Ah, I think your issue here is that you're running `make` inside of a sub-folder. It has to actually be run from the main folder, in this case `policyengine-app`. Unfortunately I can't see if the entire directory will pass lint checks until approving, so I will approve, but if the lint check fails, I'll ask you to change directories back to the main one and re-try `make format`.

**Review by anth-volk — APPROVED** [review]

**Comment by Ali-Aldawoodi** [comment]
Ohhh I see ! It looks like it merged so I assume everything was okay. Thanks for the insight, I'll keep this in mind next time. And appreciate your patience with my first contribution.

**Pull request merged**
