### PR TITLE
#529 update hover card

### PR DESCRIPTION
**Pull request by QianruZhang78**
### Summary
📊🗣️🔎

Improve messages for small inequality effects in `InequalityImpact` component. The change clarifies the reform's impact on different income inequality measures in `src/pages/policy/output/InequalityImpact.jsx`.

> _To measure the reform's effect_
> _On income inequality, we select_
> _The Gini and the share_
> _Of the top groups that fare_
> _Better or worse, and we correct_

### Walkthrough
*  Add conditional statements to display more precise messages for small impacts on inequality measures ([link](https://github.com/PolicyEngine/policyengine-app/pull/532/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L93-R95), [link](https://github.com/PolicyEngine/policyengine-app/pull/532/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L108-R112), [link](https://github.com/PolicyEngine/policyengine-app/pull/532/files?diff=unified&w=0#diff-fe27a57d57fd55796f24a1607682aea120c22c755b5843ee7dab9613a33a5c82L123-R129)) in `src/pages/policy/output/InequalityImpact.jsx`

### CODE REVIEW

**Comment by QianruZhang78** [comment]
Screen Shot 2023-05-10 at 1 41 21 PM
Hi Max, is this what you are looking for? If this looks ok I will make the necessary changes to other hover cards as well:) @MaxGhenis

**Comment by MaxGhenis** [comment]
Could you have it say "increase/decrease" rather than "impact"?

**Comment by QianruZhang78** [comment]
> Could you have it say "increase/decrease" rather than "impact"?

Screen Shot 2023-05-12 at 2 20 22 AM

Better this time? If so I‘ll make changes to other hover cards accordingly

**Comment by QianruZhang78** [comment]
Screen Shot 2023-05-13 at 2 35 00 AM
Seems like sometimes the hover cards will conflict with the title, I'll update the title accordingly as well.

**Comment by QianruZhang78** [comment]
Screen Shot 2023-05-13 at 2 26 57 AM
These are the component I've updated.

Screen Shot 2023-05-13 at 2 35 00 AM
This is an example from PovertyImpactByGender.

**Review by nikhilwoodruff — APPROVED** [review]
Looks great- thanks @QianruZhang78!

**Pull request merged**
