### PR TITLE
US election banner

### LINKED ISSUE #2142: US election banner
A banner to showcase work so far on 2024 US election

### PR DESCRIPTION
**Pull request by anth-volk**
## Description

Fixes #2142. 

## Changes

Creates new US election banner for the US site.

## Screenshots

https://github.com/user-attachments/assets/939b44e8-756a-4bfa-a0a5-f0b5af34904d

## Tests

N/A

### CODE REVIEW

**Comment by anth-volk** [comment]
Would love particular review of the following:
* Is the article button text satisfactory? Each has a long and short form, I tried to show both in the recording
* Do we want the buttons colored differently?
* Does the hero image work?

**Comment by anth-volk** [comment]
Here's the component as of now

https://github.com/user-attachments/assets/3bca2205-b1d8-408b-b6e6-96f3da2c883f

**Comment by anth-volk** [comment]
And here's a better demonstration of its responsivity

https://github.com/user-attachments/assets/991e7ef8-51a7-4520-923b-1194b720a24b

**Comment by anth-volk** [comment]
Looks like it didn't load, trying again
[AwesomeScreenshot-10_28_2024,7_18_20PM.webm](https://github.com/user-attachments/assets/dd0f602b-5505-4e88-9c2b-13ac37ac9917)

**Comment by MaxGhenis** [comment]
Looks great - can we merge without the remaining two articles for now?

**Comment by anth-volk** [comment]
The two buttons would remain links to nowhere. If that's alright, sure; alternatively, I could remove the two buttons for the missing articles early tomorrow, then take the remaining three primary articles and extend their size to fill the void.

**Comment by MaxGhenis** [comment]
I meant to remove the buttons

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
