### PR TITLE
Added internal scroll for twitter embed

### LINKED ISSUE #1511: Twitter feed in footer is too big
It's several pages of scrolling. Can it have an internal scroll? If not, let's just do 1-3 tweets to keep the footer from expanding.

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes #1511 

- Wrapped Twitter embed Component in a div and added styling to the div

https://github.com/PolicyEngine/policyengine-app/assets/46224156/e9efc590-b6a3-439b-a4b5-3280f0a146ab

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this, @dotslashbit, I appreciate you taking this on as I can't even see this component, despite being logged in. 

Is there any way to have the scroll sit inside the Twitter component itself so that the header bar that says "Tweets from @ThePolicyEngine" can be perpetually visible, as well as the container within which the tweets sit?

**Comment by dotslashbit** [comment]
https://github.com/PolicyEngine/policyengine-app/assets/46224156/c862c9b3-33eb-48e4-a272-6faa530cd9f0

**Comment by dotslashbit** [comment]
@anth-volk Let me know, if its fine or there's some more changes to be done, thanks

**Comment by anth-volk** [comment]
Good to see from this video that the current `data-width` setting of "100%" doesn't work, either. Okay, could you drop `data-height` to "450px" (ideally, it should end above the social buttons, in my opinion) and the `data-width` to something like `300px` and send again?

**Comment by dotslashbit** [comment]
https://github.com/PolicyEngine/policyengine-app/assets/46224156/8c719321-5a14-41c4-aa0c-07765361cb8f

**Review by anth-volk — APPROVED** [review]

**Comment by anth-volk** [comment]
That is perfect, thank you.

**Pull request merged**
