### PR TITLE
Remove deprecated console log in About.jsx

### LINKED ISSUE #1739: Remove deprecated console log in `About.jsx`

### PR DESCRIPTION
**Pull request by shaunakwagh**
## Description
Fix #1739 
## Changes
removed the console log in About.jsx
## Tests

no new test added

### CODE REVIEW

**Comment by anth-volk** [comment]
Hey @shaunakwagh, just wanted to check - is this complete? I saw you closed, then reopened, so wasn't sure. You can also convert to "draft" by clicking "Convert to draft" in the top right of the PR page.

**Comment by shaunakwagh** [comment]
yes, this is complete

**Comment by anth-volk** [comment]
Perfect. I had held off reviewing as I wasn't sure.

**Review by anth-volk — APPROVED** [review]
Thanks for this @shaunakwagh! Your work on this is appreciated.

**Pull request merged**
