### PR TITLE
Redesign and rewrite mobile styling 

### LINKED ISSUE #844: Fix obscured/scrolled elements in mobile view
When on mobile viewports, currently we have two issues:

* Some elements are obscured (visible on desktop but not mobile)
* On the calculator, page navigation requires the user to constantly scroll up

### PR DESCRIPTION
**Pull request by anth-volk**
This commit reworks our current mobile styling templates so as to make the site more mobile-friendly. Fixes #844 and #877. 

In my opinion, this should be pushed after #867. After #867, this PR will likely face merge conflict errors, at which point I would need to fix the buttons (as #867 changes the default button padding and renames/rewrites certain buttons). This PR is built with those changes in mind, which is why if you preview this commit off that branch, certain buttons are slightly off padding-wise.

### Summary
📱🔎♻️

This pull request improves the responsiveness, usability, and modularity of the policy engine app, especially for mobile devices. It refactors the policy and household calculator pages, extracts and adds props to some components, adjusts the styles and layouts of some components, and hides or deletes some redundant components. It also removes some whitespace in a markdown table in a blog post.

> _We're the masters of the grid, we flex our styles with skill_
> _We search and edit variables, we shape the policy at will_
> _We optimize for mobile devices, we make the calculators shine_
> _We're the `PolicyRightSidebar`, we're the rulers of the line_

### Walkthrough
*  Add `moreOnClick` prop to `NavigationButton` component to enable extra functionality on click ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-fc3284b09378d8360c8bcfe2e7e44d6cbe6c4e806becdf3ace25facd8bb619a1L7-R16), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-fc3284b09378d8360c8bcfe2e7e44d6cbe6c4e806becdf3ace25facd8bb619a1R38-R43))
*  Adjust `marginTop` style of `VariableEditor` component for mobile devices ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-0b96b3d13d96221f5cb68df970385b96da6e895d2437c2fd666a3d052401b991L83-R83))
*  Hide `BottomCarousel` component for mobile devices in `HouseholdOutput` and `PolicyOutput` components ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-ec040841afa1a198c029f240d07eb3e001304de021910e91356cc6eaafc12909L227-R233), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL663-R667))
*  Use `useDisplayCategory` hook to get display category based on window width and adjust `fontSize` and `flexDirection` styles accordingly in `NetIncomeBreakdown` and `CalculatorInterstitial` components ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-43a6b1412a31c7c18ae51a2b2ef8965d6a1b9880eea3be4c2723be4590f80fb7R15), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-43a6b1412a31c7c18ae51a2b2ef8965d6a1b9880eea3be4c2723be4590f80fb7R70), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-43a6b1412a31c7c18ae51a2b2ef8965d6a1b9880eea3be4c2723be4590f80fb7L268-R274), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-d763cec4d469980a9bb45ce22238778231f19023631cf4b26c0d5f85ff1446e8R7), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-d763cec4d469980a9bb45ce22238778231f19023631cf4b26c0d5f85ff1446e8R59-R60), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-d763cec4d469980a9bb45ce22238778231f19023631cf4b26c0d5f85ff1446e8L64-R67), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-d763cec4d469980a9bb45ce22238778231f19023631cf4b26c0d5f85ff1446e8R95))
*  Change layout of `PolicyRightSidebar` component from `flex` to `grid` and remove or modify `margin` styles of `SearchOptions` and `PolicySearch` components ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-c75e6033e75a045bd80335e28a44c550877d3ea9388a54de8b7955e9b0508285L353-R400), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-9f2cfec892507673ab493fb5f3fcd85c28b2e0aa1c2c888693695800776630d4L63-R63), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL53-R55), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-c22fbb710a983e682ce6baa65ea3b0a8866993290ef6b15a6a5aa1e29bf31a4bL77-R81))
*  Move `ParameterSearch` component from `PolicyPage` to `controls` folder and add `callback` prop ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-8ce7527c1fc25567779089488bbdfb6293b54947674805c8194705ae22d38cd1L1-R19), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-8ce7527c1fc25567779089488bbdfb6293b54947674805c8194705ae22d38cd1R39-R42))
*  Rename `MobileHouseholdPage` component to `MobileCalculatorPage` and move it to `layout` folder ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-259b16ffdd42c660e078bc66462a94024fcb77e73e53f5c830894181b81456ceL23-R23))
*  Use `MobileCalculatorPage` component for both household and policy calculators and pass `type` prop ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-259b16ffdd42c660e078bc66462a94024fcb77e73e53f5c830894181b81456ceL325-R329), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-8ce7527c1fc25567779089488bbdfb6293b54947674805c8194705ae22d38cd1L74-L338), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-8ce7527c1fc25567779089488bbdfb6293b54947674805c8194705ae22d38cd1L419-R158))
*  Add `callback` prop to `VariableSearch` component ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-635a09a9944803babc3697d505b29be2d6390491a749e02fd283a46b151fc5ecL6-R6), [link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-635a09a9944803babc3697d505b29be2d6390491a749e02fd283a46b151fc5ecR27-R30))
*  Remove whitespace in markdown table of `Budgetary impacts` section in `autumn-statement-2023` post ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-0d6c6c4c1eebb4c19624458b429dc90e8f370bbe10603dc917d6abbee84f2e4aL71-R73))
*  Delete `src/pages/household/MobileHouseholdPage.jsx` file ([link](https://github.com/PolicyEngine/policyengine-app/pull/899/files?diff=unified&w=0#diff-ce29df11a42597069e1a9d606d42f3d01c352cd25458b1acc37ad89a9d937a9c))

### CODE REVIEW

**Review by nikhilwoodruff — CHANGES_REQUESTED** [review]
Some comments here- looks amazing.

image

- Can we get the chart to fill the space sensibly?

- Can we use the drawer from antd for the new menu?

image

- Can we avoid centering horizontally?

**Comment by anth-volk** [comment]
I'm going to convert this to a draft PR so that it doesn't re-run actions every time I commit

**Review by nikhilwoodruff — APPROVED** [review]

**Comment by anth-volk** [comment]
A Loom video of what these edits do in mobile is available at https://www.loom.com/share/4af0bc7cae8d435d9f51c0e0549c50a9?sid=c2b00346-ad40-4fab-8adc-bfff547b78bb. Please note that the reason there are two scroll boxes at some points in the video is that I selected a simulated mobile device longer than my desktop browser screen.

**Comment by anth-volk** [comment]
@nikhilwoodruff was hoping you might be able to review this second round of edits.

**Review by nikhilwoodruff — APPROVED** [review]
Video looks great- thanks @anth-volk!

**Pull request merged**
