### PR TITLE
Create policy impact breakdown page

### LINKED ISSUE #35: Create policy reform overview page
With the four big numbers from the current

### PR DESCRIPTION
**Pull request by anth-volk**
## Description

Fixes #35. This PR creates a new policy impact breakdown page and inserts it into the calculator flow as the first page that the user accesses after clicking `CALCULATE ECONOMIC IMPACT`. The page is accessible from a new focus item called `policyOutput.policyBreakdown`.

## Changes

This PR:
* Creates a new component inside of the `.../policy/output` folder entitled `PolicyBreakdown` that creates the policy breakdown page
* Replaces the portion of the policy calculator flow whereby the user presses `CALCULATE ECONOMIC IMPACT` and is shown a matrix of output options with the policy breakdown page
* Adds a navigation item on the left-hand panel to access the policy breakdown page
* Updates the BottomCarousel to navigate correctly to the next policy output page

## Screenshots

A Loom video of the PR is available at https://www.loom.com/share/86802126f26b46fa960c0469f52bd3a0?sid=01bf38b2-7bca-41df-a193-b5f4a94e68c5

I realize that much of this wording, formatting, etc., may not be 100% perfect, and am very open to making edits to better suit the overall application.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Awesome, thanks Anthony. What do you think about this text?

```
Your reform impact in the US over 2024
  {Costs,Raises} $x billion
  {Increases, Lowers} poverty x% [or Does not affect poverty]
  Raises the net income of x% of the population
  Lowers the net income of x% of the population
```

We can also drop the arrows. We've gotten feedback that they're confusing on the household page, and I think they'd be at least as confusing here.

**Comment by MaxGhenis** [comment]
Actually how about we unify the winners/losers message as I suggested in the chart title here https://github.com/PolicyEngine/policyengine-app/pull/1069#issuecomment-1872543897

**Comment by anth-volk** [comment]
Can do, will revise probably tomorrow.

**Comment by anth-volk** [comment]
As an update, I'll be working on this later in the week in favor of building out authentication on the light API

**Comment by anth-volk** [comment]
Would you want to drop the coloring on the numbers, as well? Or maintain that?

**Comment by MaxGhenis** [comment]
let's keep the coloring

**Comment by anth-volk** [comment]
Loom video of the new component available [here](https://www.loom.com/share/20acd80ede914ad4a086178dd2f7958c?sid=b58efb85-14cf-4279-bf95-cded30c7422b).

**Comment by anth-volk** [comment]
Open to any styling and/or formatting changes

**Review by nikhilwoodruff — APPROVED** [review]

**Pull request merged**
