### PR TITLE
chore: enable recommended ESLint plugin rules

### PR DESCRIPTION
**Pull request by nschonni**
Turn on the recommended set of rules for the current plugins and turn off the currently failing rules. The rules should be enabled/fixed later.

### Summary
:wrench::sparkles::recycle:

This pull request improves the linting configuration for the project by updating the `.eslintrc.json` file and removing the `eslintConfig` property from the `package.json` file. These changes enhance the code quality, accessibility, and testing of the React app.

> _To make our code linting more pleasant_
> _We removed `eslintConfig` from `package.json`_
> _And updated `.eslintrc.json` with care_
> _To fix some issues and make rules more fair_
> _Now our code quality is more consistent_

### Walkthrough
*  Configure ESLint for React, React Hooks, and accessibility rules ([link](https://github.com/PolicyEngine/policyengine-app/pull/681/files?diff=unified&w=0#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fL5-R16))
*  Move Jest plugin settings to test file overrides ([link](https://github.com/PolicyEngine/policyengine-app/pull/681/files?diff=unified&w=0#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fL25-R25), [link](https://github.com/PolicyEngine/policyengine-app/pull/681/files?diff=unified&w=0#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fL5-R16))
*  Simplify plugin loading and disable some recommended rules ([link](https://github.com/PolicyEngine/policyengine-app/pull/681/files?diff=unified&w=0#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fL32-R45))
*  Remove redundant `eslintConfig` property from `package.json` ([link](https://github.com/PolicyEngine/policyengine-app/pull/681/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L58-L63))

### CODE REVIEW

**Comment by anth-volk** [comment]
@nschonni Apologies for the delay in addressing this PR. Would you mind providing a bit of context as to what/why things were failing? I joined a bit after this issue and am wondering if it's still relevant. Thanks so much.

**Comment by anth-volk** [comment]
@nikhilwoodruff Should we move ahead with this?

**Comment by nikhilwoodruff** [comment]
Yep I think this is still worthwhile!

**Comment by abhcs** [comment]
I had not seen this PR before writing PRs #1080 and #1098 (sorry about the overlap!).

The first change in the new PRs is the use of the [eslint-react-app config](https://github.com/facebook/create-react-app/blob/main/packages/eslint-config-react-app/README.md). This includes accessibility checks and optional jest rules (that I have not activated).

The second change is that I have not disabled any rules but instead fixed the errors in the code.

In light of these changes, we have to figure out which parts of this PR still apply or need modification. I can see that the Jest and jsx-a11y parts still apply but disabling is not needed for many of the rules.

**Comment by anth-volk** [comment]
Thanks for your input, @abhcs, I had meant to raise this with you early next week as I went through cleaning out a few almost-stale PRs. Since you teed it up, though, do you think there's value in separating out these recommended plugins as separate PRs? I'm anticipating that at least in a couple cases, there should be some pretty significant fixes that would have to be implemented should we activate them.

**Comment by abhcs** [comment]
"plugin:jest/recommended" has been enabled properly in this PR by fixing the errors.

"plugin:jsx-a11y/recommended" has been enabled too but by disabling some of the rules. I am not sure what rules lie in

"plugin:jsx-a11y/recommended" - "react-app" - {disabled rules in this PR}.

If this set is non-empty, then there is value in adding "plugin:jsx-a11y/recommended" with the disabled rules. For simplicity, we can ignore "plugin:jsx-a11y/recommended" in this PR and handle it separately. As you point out, enabling the rules will require significant effort.

**Comment by anth-volk** [comment]
Because of the previous PR, this PR is now also like 50% merge conflicts...

@abhcs What if instead we close this, then you open a new one enabling `plugin:jest/recommended` first; we merge that, then move to `a11y` with an aim toward actually meeting all of the rules (if you're willing to take on that herculean task)? 

Alternatively, would you be willing to handle the merge conflicts of this PR, drop `a11y`, and ensure that `jest/recommended` still functions properly?

And what of the `prettier` plugin?

**Comment by abhcs** [comment]
> "plugin:prettier/recommended" runs Prettier as an ESLint rule and reports differences as individual ESLint issues.

This would be valuable if we were using prettier *through* eslint but we are using prettier *with* eslint everywhere. So, it can be ignored.

How about the following suggestion? I can open a PR that enables the plugins `a11y` and `jest` but with the following offending rules disabled:
~~~js
    "jsx-a11y/mouse-events-have-key-events": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off"
~~~
 and with @nschonni 's fixes for `jest`.

Then, you can open four new issues -- one for each of the rules -- hopefully someone will volunteer and fix the rules one by one.

**Comment by anth-volk** [comment]
@abhcs Thanks for the details on prettier, and that sounds like a great plan

**Comment by anth-volk** [comment]
Superseded by #1114. Closing.

**Pull request closed without merging**
