### PR TITLE
Make markdown show

### LINKED ISSUE #1703: AI prompt doesn't load
Example - this shows even when the microsim completes

https://policyengine.org/uk/policy?focus=policyOutput.analysis&reform=3177&region=uk&timePeriod=2024&baseline=1

image

### PR DESCRIPTION
**Pull request by czhou578**
## Description

Fixes #1703 
Please provide a summary of the changes and which issue is fixed. Please include relevant motivation and context.

## Changes

This PR ensure that the prompt in the ```Analysis.jsx``` file is correctly displayed once the user clicks "Show Prompt" on the UI.

## Screenshots

image

## Tests

No new tests were added.

### CODE REVIEW

**Comment by czhou578** [comment]
@anth-volk, I'm not sure if this is how you want the text to be displayed in markdown. Is this how its supposed to be?

**Comment by anth-volk** [comment]
Funky seeing our 35th president editing his policy provisions on PolicyEngine haha.

It looks like one of the asterisks in the first line (in "I'm") is causing the strange display. Could you check into either fiddling with the settings so that that doesn't happen (the relevant package is CodeMirror on NPM, I believe) or somehow sanitizing it?

**Comment by czhou578** [comment]
Does this work?
image

**Comment by anth-volk** [comment]
That looks good!

**Comment by MaxGhenis** [comment]
Can we please fix this before 9am ET tomorrow? @nikhilwoodruff could you tag in if needed?

**Comment by anth-volk** [comment]
I've just spent an hour or more on this and still don't understand why this test is failing - it's as if, when run, Jest clips all code below line 30 in the CodeMirror component, even though it's absolutely visible. I'm going to try to fix this soon, but if I can't find a resolution within the next 15-20 minutes, it'd be best to disable these tests.

**Comment by anth-volk** [comment]
Actually, I think I have a workaround for this

**Comment by nikhilwoodruff** [comment]
Sorry I didn't see this! Just got it working in #1743 but this looks like a nicer solution

**Comment by nikhilwoodruff** [comment]
@anth-volk- the tests are passing fine on my PR oddly

**Comment by nikhilwoodruff** [comment]
Thanks @czhou578 and sorry for stealing your PR :) - I think #1754 can get this over the line. Just added your line wrapping extension to it.

**Comment by nikhilwoodruff** [comment]
OK so I spoke too soon

**Comment by anth-volk** [comment]
Just got the tests working

**Comment by anth-volk** [comment]
It does look good. Once these pass, I'll merge

**Review by nikhilwoodruff — APPROVED** [review]

**Comment by anth-volk** [comment]
And we're good

**Pull request merged**
