### PR TITLE
Re-added featured tag to various US articles

### LINKED ISSUE #1546: Re-add `featured` tag to various US articles
After the completion of #1515, we should re-add the `featured` tag within `posts.json` to the articles that had it removed in #1516.

### PR DESCRIPTION
**Pull request by Suvid-Singhal**
## Description

Added the featured tag to all the articles that had it removed in #1516
Fixes #1546

## Tests

Passes all the tests.

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for your work on this, @Suvid-Singhal. Unfortunately, as noted in the issue (#1546), this cannot be merged until #1515 is completed. That is currently in progress from another developer. That said, once that's completed and merged, we can take a look at these contributions. Thank you very much.

**Comment by MaxGhenis** [comment]
https://github.com/PolicyEngine/policyengine-app/pull/1702 was closed, not merged.

**Comment by anth-volk** [comment]
@Suvid-Singhal Apologies for the delay on this, this issue was de-prioritized in favor of a few bigger ones. I will be checking back into this soon.

**Review by anth-volk — APPROVED** [review]
Confirmed that this is working. Thanks for your work, @Suvid-Singhal, apologies for this going dormant as long as it did. Once the CI finishes, this will be merged, barring an error.

**Comment by Suvid-Singhal** [comment]
My pleasure :)

**Pull request merged**
