### PR TITLE
Add tests for issue #249

### PR DESCRIPTION
**Pull request by PGrad**
# New feature/Improvement/Bug fix: Adds tests for issue #249 

This submission adds some tests in jest that confirm the current behavior implemented in #249: that the user is directed to the UK page if they enter an invalid country code, and directed to a 404 page if they give a bad url under one of the country pages. Tests ensure that the website continues to behave as expected.

Adds jest, react-testing-library, and jsdom as devdependencies in the package.json. This submission also adds a new Github action that automatically runs the tests when pushing to a PR.

### Status
* [x]  Cosmetic change
Moves the top margin of the 404 page up a bit.
   
* [ ]  Screenshots attached
* [ ]  Back-end change
* [ ]  Unintuitive logic commented
* [ ]  Version change   
  * [ ]  Major
  * [ ]  Minor
  * [ ]  Patch
 
### Issues fixed
None

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Amazing, thanks for making a start on our (very overdue by me) React test suite! Do you think you could add a GitHub action that runs the checks? Happy to take a look here too.

**Comment by PGrad** [comment]
> Amazing, thanks for making a start on our (very overdue by me) React test suite! Do you think you could add a GitHub action that runs the checks? Happy to take a look here too.

Yeah, I can get an action started tomorrow. There's a lot of stuff to test, I don't know if you have a roadmap or test plan.

**Comment by PGrad** [comment]
@nikhilwoodruff Hey Nikhil, I created the Github action and the tests now run automatically when pushing to a PR.

**Comment by nikhilwoodruff** [comment]
> > Amazing, thanks for making a start on our (very overdue by me) React test suite! Do you think you could add a GitHub action that runs the checks? Happy to take a look here too.
> 
> Yeah, I can get an action started tomorrow. There's a lot of stuff to test, I don't know if you have a roadmap or test plan.

Perfect- sorry yes not at the moment. But this looks amazing, thanks!

Only minor thought is maybe we could just test on the latest node version? But I'm keen to merge this and I don't think there's any downside to covering these four.

**Pull request merged**
