### PR TITLE
fix: removed unnecessary logs

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

Please provide a summary of the changes and which issue is fixed. Please include relevant motivation and context.
Fix: [#984](e/policyengine-app/issues/984) 

## Changes
removed log statements from PolicyOutput.jsx and BudgetaryImapact.jsx

### CODE REVIEW

**Review by anth-volk — APPROVED** [review]
This is perfect! Thanks so much, @dotslashbit.

**Comment by anth-volk** [comment]
Before I merge this, could you run `make format` and push again? This is to lint our files.

**Comment by dotslashbit** [comment]
@anth-volk I ran make format and updated the PR, if there's any correction to be made, then please let me know

**Comment by anth-volk** [comment]
Looks like there's currently a conflict. You might be running off of an older version of our `master` branch. Could you also rebase off of master and push again?

**Comment by dotslashbit** [comment]
@anth-volk is there any issue?

**Comment by anth-volk** [comment]
Just had to re-lint after rebasing, unfortunately

**Comment by dotslashbit** [comment]
Thanks

**Pull request merged**
