### PR TITLE
Checkbox to include earning variation in Python reproduction

### PR DESCRIPTION
**Pull request by jacky5124**
This PR is to address issue #349.

A new generic Checkbox component is added, and it is used in the HouseholdReproducibility component to allow users switch between producing only net income and producing earning variation. The functionality has been achieved, but the checkbox description text and its style are to be improved. Any feedback will be appreciated!

changeToInclude

changeToNotInclude

### Summary
✨🎨🧱

Added a feature to `HouseholdReproducibility` to enable earning variation in household simulation. Created a new `Checkbox` component to handle checkbox inputs.

> _To render a checkbox with ease_
> _A new component `Checkbox` was made_
> _It takes props for label and state_
> _And calls `onChange` when clicked or swayed_
> _It helps with the household sim update_

### Walkthrough
* Create a new `Checkbox` component to render a checkbox input with a label ([link](https://github.com/PolicyEngine/policyengine-app/pull/474/files?diff=unified&w=0#diff-2cf378a1706b6c9dad3885a17e0e873a08e2a99e517558db1ee62d17e59240d0R1-R13))
* Import `Checkbox` and `useState` in `HouseholdReproducibility` component ([link](https://github.com/PolicyEngine/policyengine-app/pull/474/files?diff=unified&w=0#diff-27695a8486f76672e2544cc7d9e8cb5f4548260da07d6954330c2c605fdca50dL1-R4))
* Add a state variable `earningVariation` to toggle earning variation feature in household simulation ([link](https://github.com/PolicyEngine/policyengine-app/pull/474/files?diff=unified&w=0#diff-27695a8486f76672e2544cc7d9e8cb5f4548260da07d6954330c2c605fdca50dR88))
* Modify household input copy logic to conditionally delete `employment_income` and add `axes` parameter based on `earningVariation` value ([link](https://github.com/PolicyEngine/policyengine-app/pull/474/files?diff=unified&w=0#diff-27695a8486f76672e2544cc7d9e8cb5f4548260da07d6954330c2c605fdca50dL113-R126))
* Add a UI element using `Checkbox` to allow user to enable or disable earning variation feature ([link](https://github.com/PolicyEngine/policyengine-app/pull/474/files?diff=unified&w=0#diff-27695a8486f76672e2544cc7d9e8cb5f4548260da07d6954330c2c605fdca50dR156-R168))

### CODE REVIEW

**Review by nikhilwoodruff — COMMENTED** [review]
Thanks- could we just ensure the checkbox text has the same style as the main description text?

**Comment by MaxGhenis** [comment]
Could we make it a switch instead, for consistency with other elements like policy abolition?

**Comment by jacky5124** [comment]
Sure that sounds great! I will change the checkbox to a switch, like the ones on policy abolition pages.

**Comment by jacky5124** [comment]
Changed the checkbox to a switch, reverted the font size of the switch's text back to normal, and made the style of the title and description of "Reproduce in Python" consistent with the other three result panels.

toInclude

toNotInclude

**Review by nikhilwoodruff — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
