### PR TITLE
Subscribe button on homepage

### LINKED ISSUE #598: Subscribe button on homepage
Just below the blog carousel

### PR DESCRIPTION
**Pull request by sohaibaumer**
Fixes #598 

- Renamed the branch/commit as per requirement.

- Screenshot is also attached:
Fixes-#598 Subscribe button on homepage

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks - looks nice. Could you please:
* Zoom out for the screenshot so we can see where the content below is
* Add a mobile screenshot
* Remove `Fixes #598` from the PR title and move it into the PR description (the first comment, which you can edit)

**Review by nikhilwoodruff — APPROVED** [review]
Thanks @sohaibaumer - looks great. I made a few style changes (fixing centering and removing the top white gap). I couldn't immediately figure out the test issue though, do you have any ideas what changed?

**Comment by sohaibaumer** [comment]
@nikhilwoodruff 
not sure, I re-ran the test and they pass.
image
PS, I didn't change much in code anyways, re-used one of your existing functions.

**Comment by MaxGhenis** [comment]
Any update here? Could you try pulling in the latest changes to see if that affects CI?

**Comment by MaxGhenis** [comment]
What's the status on this?

**Comment by anth-volk** [comment]
I wrote a PR last week that creates this functionality, but it could probably be made more robust with front-end authentication practices in the future. I believe Nikhil has pushed the code into prod.

**Comment by anth-volk** [comment]
Closing, as this functionality was added with #924.

**Pull request closed without merging**
