### PR TITLE
Policy output info modal appears every time

### LINKED ISSUE #2025: Policy output info modal appears every time
This has been bugging me for ages.

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #2025

cc @anth-volk

### CODE REVIEW

**Comment by anth-volk** [comment]
@nikhilwoodruff Could you remove the unused import of `setCookie`?

**Comment by anth-volk** [comment]
I'm sorry, I meant the `import {..., setCookie}` in PolicyImpactPopup, but it's fine, I can take it out

**Comment by anth-volk** [comment]
Your changes just kind of ripped the entire function out

**Review by anth-volk — APPROVED** [review]

**Comment by nikhilwoodruff** [comment]
Thanks!!

**Pull request merged**
