### PR TITLE
Removed Carousel From Mobile View

### LINKED ISSUE #1945: Second set of navigation arrows present on mobile
See https://www.loom.com/share/93897aa39c9c4cfc8e6646e50cebf333 - the set of arrows that is present in the middle of the page should not be

### PR DESCRIPTION
**Pull request by rachel-lawrie**
Added logic to does not display BottomCarousel component for mobile. Removed irrelevant code for mobile in the BottomCarousel Component.

## Description

Fixes #1945. Added logic to does not display BottomCarousel component for mobile. Removed irrelevant code for mobile in the BottomCarousel Component.

## Changes

Added logic to does not display BottomCarousel component for mobile. Removed irrelevant code for mobile in the BottomCarousel Component. Changed component name to BottomImpactDescription since it is no longer a carousel.

## Screenshots

https://www.loom.com/share/2b4e66f64dcd47a7a2b6fabf00dc8a1c

## Tests

I don't think Jest tests are too relevant so I went through full UI for type = 'household' and type = 'policy' for both US and UK versions of the app. Ran npm tests and no new tests fail (outside of the 8 that were failing prior to the change).

### CODE REVIEW

**Comment by rachel-lawrie** [comment]
@anth-volk the relevant component for web is labeled BottomCarousel, even though it is not a carousel. Should I rename to something else? Like "BottomImpactDescription"? I explain with a visual what I am talking about in the Loom.

**Comment by anth-volk** [comment]
@rachel-lawrie Good point, could you go ahead and do so as part of this PR? If you could also open a new issue for it and link it here.

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for this @rachel-lawrie. This is great, could you just clean up the linter errors?

**Review by anth-volk — APPROVED** [review]
Thanks @rachel-lawrie, these look great! Glad to get this bug taken care of.

**Pull request merged**
