### PR TITLE
Make you are here on household charts a point instead of line

### LINKED ISSUE #611: Make `you are here` on household charts a point instead of line
This third vertical line repeatedly confuses users. We should instead make a `you are here` semi-transparent point on the baseline graph, and a second (blue) point on the reform graph. They probably don't need to be in the legend.

https://policyengine.org/us/household?focus=householdOutput.earnings&household=32121&region=us&timePeriod=2023&baseline=2&reform=17331

image

### PR DESCRIPTION
**Pull request by patrickhanl**
Fixes #611

### Summary
🧪📊🛠️

This pull request enhances the BaselineAndReformChart component, which shows the impact of policy reforms on a household's income. It adds a baseline prop, switches to scatter traces, and updates the hover card. It also adds a test file for the component, which checks the toggle button.

> _`BaselineAndReformChart` shows us the fate_
> _Of the households under different policies_
> _We mock the api and the plotly trace_
> _To test the toggle and the hover messages_

### Walkthrough
*  Add a new prop `baselineValue` to `BaselineAndReformTogetherPlot` component to show the baseline value on the chart ([link](https://github.com/PolicyEngine/policyengine-app/pull/652/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bR148))
*  Replace line traces with scatter traces for the current and baseline values of the variable in `BaselineAndReformTogetherPlot` component to improve the plot appearance and clarity ([link](https://github.com/PolicyEngine/policyengine-app/pull/652/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL177-R198))
*  Adjust the hover card message for the points on `BaselineAndReformTogetherPlot` component to indicate whether they belong to the reform or the baseline scenario ([link](https://github.com/PolicyEngine/policyengine-app/pull/652/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL232-R245))
*  Replace line trace with scatter trace for the change in the variable value in `BaselineReformDeltaPlot` component to improve the plot appearance and clarity ([link](https://github.com/PolicyEngine/policyengine-app/pull/652/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL291-R309))
*  Add a test file `BaselineAndReformChart.test.js` for the `BaselineAndReformChart` component, which checks the toggle button functionality using a mock metadata object and api functions ([link](https://github.com/PolicyEngine/policyengine-app/pull/652/files?diff=unified&w=0#diff-ea82f6e985b4405746178eb385dfa12dba2ec298d08ea4e73718a83dc0f5eee3L1-R45))

Changed the baseline and reform comparison charts to have separate points for baseline and reform based on current variable value.

They appear in the legend by default so I left them in for now but can take out if not needed.

baseline-reform
delta

Also added test cases.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thank you @patrickhanl! The baseline and reform view looks perfect. On the difference plot, could you remove the line from the legend entry for the you are here series? Also could you show a screenshot of a scenario without a reform?

**Comment by patrickhanl** [comment]
> Thank you @patrickhanl! The baseline and reform view looks perfect. On the difference plot, could you remove the line from the legend entry for the you are here series? Also could you show a screenshot of a scenario without a reform?

@MaxGhenis , I wasn't sure if you wanted the baseline only updated since it doesn't have the issue of multiple lines, so that looks the same (see below). I can make that update pretty quickly if you want it updated as well. I'll push the legend update with that if so.

baseline-only

**Comment by MaxGhenis** [comment]
yes please do it for baseline only as well

**Comment by patrickhanl** [comment]
@MaxGhenis please see screenshots below with hovercards for updated plots. Let me know if you see anything else that needs to be fixed. Not sure exactly why the CI check is failing? Looks like the request to the Node server is failing?

Baseline and Reform together plot
base-hover-reform

base-reform-hover

Baseline and Reform delta plot
diff-hover

Baseline only plot
baseline-only-hover

**Comment by MaxGhenis** [comment]
Thanks @patrickhanl, all looks good here. Just looks like a nodejs.org issue holding back the CI: https://github.com/nodejs/nodejs.org/issues/4495#issuecomment-1666920255

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
The nodejs.org issue resolved itself, so merging. Thanks!

**Pull request merged**
