### PR TITLE
removed multiple scrolls from household output page

### LINKED ISSUE #994: `Reproduce in Python` page has three different scroll containers
One each for the code block itself, the div surrounding the main content, and the entire middle panel

### LINKED ISSUE #1284: Multiple Scrolls on Household Python Reproduce page
Screenshot 2024-01-26 at 12 07 17 PM

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes #1284 

fixes #994 

## Screenshots

Screenshot 2024-02-02 at 10 57 52 AM

### CODE REVIEW

**Comment by dotslashbit** [comment]
@anth-volk I think this also solves #994

**Review by anth-volk — CHANGES_REQUESTED** [review]
This is great, @dotslashbit, and this issue has driven me crazy for quite a while. That said, I'm wondering if a minor change is possible: is it possible to move the scroll parameter to the parent of this `pane` element? As you can see in these screenshots, if the scroll is on this part, the scroll bar isn't quite in the expected position:

Screen Shot 2024-02-02 at 8 39 44 PM
Screen Shot 2024-02-02 at 8 39 49 PM

Whereas, if the scroll is applied to the parent manually in the console, it looks like the below and still functions correctly:

Screen Shot 2024-02-02 at 8 40 06 PM
Screen Shot 2024-02-02 at 8 40 07 PM

**Comment by anth-volk** [comment]
Also, I think you're right @dotslashbit, this does solve #994. Could you edit your first comment that you used to open the PR to say that?

**Comment by dotslashbit** [comment]
@anth-volk updated the code as required

**Review by anth-volk — APPROVED** [review]
Thanks a ton for this, @dotslashbit. I took the liberty of making a minor change and pushing it on top (just adjusting a container scroll). This is great to have, thanks for the contribution.

**Pull request merged**
