### PR TITLE
Make each policy provision a sentence #88

### LINKED ISSUE #88: Make each policy provision a sentence
How about replacing the current with this in the right panel (soon to be carousel thanks to @DeepthiSRao)?
>Raise the Ofgem Energy Price Cap from **£70** to **£80**
_2022-01-01 to 2027-12-31_

Where £70 could be gray and £80 could be blue

### PR DESCRIPTION
**Pull request by DeepthiSRao**
Fixes #88

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Could you display `Enable` if `value` is `true`, otherwise `Disable`?

**Comment by DeepthiSRao** [comment]
PE_Issue88_1
PE_Issue88_2

**Comment by MaxGhenis** [comment]
Please remove the "from..." on the enable/disable sentences

It should just be "Enable abolition" or "Disable abolition" with Enable/Disable in bold+blue

(Separately, we should make this particular parameter more descriptive...)

**Comment by MaxGhenis** [comment]
Thanks - last thing, could you please center it? I think that's usually the more natural layout when there's a carousel.

**Comment by DeepthiSRao** [comment]
image

**Pull request merged**
