### PR TITLE
fix: removed blue higlight from button text

### LINKED ISSUE #1184: Buttons that contain text getting Blue Highlight
If you drag your mouse on the text of any button, you'll see the blue highlight

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes #1184 

added the same changes to button as arrowbutton

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/46224156/1f0317f0-6be5-4451-9dab-c5557a4b7bf1

### CODE REVIEW

**Comment by dotslashbit** [comment]
@anth-volk I think the top right button "Compute Policy Impact" should be wrapped with Button component. Currently the changes are working for this top right button.
Waiting for your input

**Comment by dotslashbit** [comment]
@anth-volk Updated the code as required

**Comment by anth-volk** [comment]
@dotslashbit Thanks, will review tomorrow

**Review by anth-volk — APPROVED** [review]
Thanks @dotslashbit! This works great.

**Pull request merged**
