### PR TITLE
Improve author filtering

### LINKED ISSUE #1555: Issues with author filtering when at bottom of Research page
If a user is at the bottom of the Research page and decides to remove an author with many articles (e.g., Nikhil Woodruff) from the left-hand filter bar, they're jammed downward into the footer, instead of a more graceful handling of this situation. This is visible in the video below. Ideally, the user would be positioned at the last post that is now visible.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/d5d10771-40f0-4b37-99ad-f496ed171e6f

### PR DESCRIPTION
**Pull request by NishantSatere**
## Description

Fixes #1555. Instead of redirecting the user to the bottom of the page upon filtering by author, the page should refresh and maintain its position at the top, or even better, it should redirect the user to the top where the newly filtered posts are displayed. This adjustment will enhance the user experience by allowing immediate access to the relevant, filtered content without the need to scroll up manually.

## Changes
I have implemented a line of code that ensures redirection to the top of the page whenever any checkbox is toggled. This solution effectively addresses the issue by providing users with instant access to the filtered content without disrupting their browsing experience.

## Screenshots

Please include concise visuals (videos, screenshots, etc.) demonstrating the code in action and the impact of changes. Many on the team use a free tool called [Loom](https://www.loom.com/) to capture and share short clips, but feel free to utilize any tool you'd like. Screenshots of the code itself can also be helpful, but are usually not necessary.

Authors checkbox video demo:

https://github.com/PolicyEngine/policyengine-app/assets/100207648/1b6d11d8-4fea-4757-a28f-f31066ce7116

## Tests

Location checkbox demo:

https://github.com/PolicyEngine/policyengine-app/assets/100207648/409d9a26-ac0b-461e-b49e-2d2f6a4921d5

Topic checkbox demo:

https://github.com/PolicyEngine/policyengine-app/assets/100207648/64b4ee6a-659b-44e9-b5b4-1eebf1de72c3

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this contribution, @NishantSatere! Before I review, could you add a line like "Fixes #1555" to the PR description? This helps to auto-close the issue when merged. Additionally, does this address #1554? If so, please add that, as well.

**Comment by NishantSatere** [comment]
i have changed the description of the PR and also i am working on the issue #1554, but i have some doubts, want to discuss with you @anth-volk . How can i connect with you ?.

**Comment by anth-volk** [comment]
If you could send a link to an account of yours on another platform, I could send you a link to join our Slack. How does that sound to you?

**Comment by MaxGhenis** [comment]
Please change the description not the title. See other PRs as examples.

**Comment by anth-volk** [comment]
Also, to be clear, I was hoping you could add "Fixes #1555" to the description, not the title. I've made the edit accordingly.

**Comment by NishantSatere** [comment]
Yes, can you please send the link of slack

**Comment by NishantSatere** [comment]
LinkedIn: https://www.linkedin.com/in/nishant-satere-397b77257/

**Comment by anth-volk** [comment]
@NishantSatere Just reached out to you there. Looking forward to chatting.

**Pull request closed without merging**
