### PR TITLE
More safely handle conditional require statements in blog post

### LINKED ISSUE #1589: More safely handle conditional `require` statements in blog post
Currently, in the `BlogPost.jsx` component, we use a conditional `require` to load blog images. However, the conditional only checks if a blog image is specified, not if it's present. I'm not sure if this is technically feasible, but it'd be great to ensure that a failing `require` statement returns some sort of empty "broken file" block, akin to what standard JS-free HTML image loading would do, as opposed to killing the entire app.

### PR DESCRIPTION
**Pull request by czhou578**
## Description

Fixes #1589 

## Changes

Added a conditional try catch block to check for the existence of a blog post image. This is done in order to handle the nonexistence of a picture in a more graceful manner. If an image does not exist, then a ```FileImageOutlined ``` icon from Ant Design is displayed at the top.

## Screenshots
image

## Tests

No new tests added.

### CODE REVIEW

**Comment by czhou578** [comment]
@anth-volk , how big do you want the missing pictures icon to be?

**Comment by czhou578** [comment]
@anth-volk, how about this?

image

**Comment by anth-volk** [comment]
What about this - in place of the image, pop in a div with a height of 300px, the same width as the image (is it 100%?), and a 1px gray border. Flexbox it, and place the icon (maybe, like, font-size 32px?) into the bottom-right corner. It's similar to what you had been thinking with the broken image icon, I think.

**Comment by czhou578** [comment]
Something like this?

image

**Comment by anth-volk** [comment]
That looks perfect to me

**Comment by czhou578** [comment]
Ok. I've pushed the changes.

**Comment by anth-volk** [comment]
Perfect, will review Monday. Thanks so much for this, @czhou578.

**Review by anth-volk — APPROVED** [review]
This is perfect, @czhou578, thank you very much!

**Pull request merged**
