### PR TITLE
fix: changed the default state to california

### LINKED ISSUE #1057: Change default state display to mirror actual default state
At the moment, when inputting a household, the state page displays a default state of "Alabama," but the actual default state is California. This should be changed, as it's very confusing if you're just clicking through.

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

closes #1057 

## Changes

changed the default state to california

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/46224156/22bc6d7a-b001-4068-bf22-6b06be3929ef

## Tests

Please describe how the change has been tested.

### CODE REVIEW

**Comment by abhcs** [comment]
The variable editor is for all variables, not just states. We should add a check that the variable is the state variable.

Maybe searching for California is better than hardcoding `2`.

@anth-volk If California is the default state, is this fact present in the model, e.g., `metadata`? If yes, then we should use the  default state in the model; otherwise, we should add this fact to the model.

**Comment by MaxGhenis** [comment]
policyengine-us sets California as the default state:

https://github.com/PolicyEngine/policyengine-us/blob/36394152bcf2820c4138a06e6c55d9e9cc78ca02/policyengine_us/variables/household/demographic/geographic/state_code.py#L68-L71

**Comment by abhcs** [comment]
@MaxGhenis Thanks for that information.

The problem should be fixed by improving the logic for extracting the default value from the model on lines 190-218. It is only when no defaults have been found that the first value is chosen by default on line 225.

@dotslashbit Do you want to try to find what goes wrong on lines 190-218, i.e., why the default state is not found there, and what the code should do instead?

**Comment by dotslashbit** [comment]
@abhcs I have improved the logic and now its getting the default state as california, please let me know if there's any correction needed, thanks for letting me work on this.

**Comment by dotslashbit** [comment]
https://github.com/PolicyEngine/policyengine-app/assets/46224156/05b8f8f0-63ef-4350-bba0-51849d5e68d1

**Comment by abhcs** [comment]
@dotslashbit so we were not reading the default variable value at all -- good catch! I think these changes are good.

Looking at the code I still think that the process for choosing the default value is overly complex. Why does it have to look through 4 options to get the default? It should just be 2. Perhaps the design of these components should be improved (not in this PR).

**Comment by dotslashbit** [comment]
@abhcs Thank you, so is it good to get merged?

**Comment by abhcs** [comment]
@dotslashbit I'm not authorized to merge requests but someone with authority will help you out in due time.

**Review by anth-volk — APPROVED** [review]
Thanks @dotslashbit, just tested and this works great.

**Pull request merged**
