### PR TITLE
Added Martin Holmer to About Page

### LINKED ISSUE #1575: Add Martin Holmer to About page

### PR DESCRIPTION
**Pull request by daemon-reconfig**
## Description

Fixes #1575 

## Changes

Added Martin Holmer to About Page

## Screenshots
image

### CODE REVIEW

**Comment by anth-volk** [comment]
Thanks for this, @daemon-reconfig. I should be able to get to this and your other PR end-of-day today, just have had some high-priority items to deal with first.

**Comment by daemon-reconfig** [comment]
thank you for helping me out as well!! @MaxGhenis thank you!

**Review by anth-volk — APPROVED** [review]
Thanks @daemon-reconfig, this is great. Everything looks good, except that because of how we position the photo, we cut off the top of Martin Holmer's head. Can you implement a simple way of adding "objectPosition: top" to only his image, but one that's programmatic? Maybe adding an optional key within the user bio object that sets objectPosition manually, then adding this styling to the JSX output? Otherwise, I think this all looks great.

**Comment by daemon-reconfig** [comment]
sure I will change the positing of the image

**Comment by daemon-reconfig** [comment]
Screenshot 2024-04-18 at 5 17 27 PM
I just cropped the image as I wasnt able to add anything to only his image 
:P

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for your work on this, @daemon-reconfig. This does look good. Normally, I would approve this, but there's two issues:

1. This PR also includes the commits you made for #1600. However, since that's a separate issue, we can't include these changes. I believe the only way to fix this would be to do the following:
* Open your `master` branch
* Run `git checkout -b <branch name>` - this will become a new PR for #1600 
* Close the existing PR for #1600 
* Open a new PR off this new branch
* Then, run `git checkout master` to switch back to master
* Run `git pull upstream master` to pull the changes that have been made to the live repo
* Run `git push origin --force master` to update your master to match the live PolicyEngine one
* Run `git checkout Mehul-#1575` to switch to this feature branch
* Run `git rebase master` to incorporate the code from `master` - this may require fixing merge conflicts
* Run `git push origin --force Mehul-#1575` to push the changes 
Alternatively, if there are too many merge conflicts for this branch, you could do all the stuff to update master, then open a new PR with these changes

2. We typically ask contributors to make commits with professional names. We don't require a specific format at the moment, but the last three commits you have don't fit within our expectations of commit names. I realize you're probably new to the field, and we can allow it this time, but in the future, please don't use names with no info (like `.`) or names that are exceptionally informal (like the `i guess...` part of your other two commits), as these make it harder to find where changes occurred if we ever have to look through the commit list.

Thanks again for all of this, @daemon-reconfig. If you want help doing the above that I mentioned in no. 1 above, we have a Slack group, and if you send a link to your LinkedIn or something else, we can connect, you can join, and I can walk you through it more easily.

**Comment by daemon-reconfig** [comment]
I am terribly sorry about the naming of the commits and I promise it wont happen again.

**Comment by anth-volk** [comment]
It's alright, no need to apologize, we all learn these things with time.

**Comment by daemon-reconfig** [comment]
I seem unable to do it. Can you please help me with it? 
[Mehul Sardana](https://www.linkedin.com/in/mehul-sardana-b1a120194?trk=contact-info) here is my linkedin 
if it’s fine you can add me on slack as well,
thank you so much!

**Comment by anth-volk** [comment]
Sure, I'll invite you, just please remind me early next week and we can set up a time.

**Comment by daemon-reconfig** [comment]
thank you so much. I am grateful for your help and would frankly ask you to help me in times of need.

**Comment by MaxGhenis** [comment]
can we merge this?

**Comment by anth-volk** [comment]
We cannot, as this contains a stub of another PR that will break all of the buttons on the household side. That said, let me just push a couple commits on top to remove that code and we'll be good.

**Review by anth-volk — APPROVED** [review]

**Pull request merged**
