### PR TITLE
Add clickability to initial microsim outputs

### LINKED ISSUE #1939: Make the three initial Microsim outputs clickable
It would be nice if it would take you directly to the respective tab 

image

### PR DESCRIPTION
**Pull request by tawandamoyo**
## Changes

Added clickability to inital microsim outputs.

## Screenshots

https://github.com/user-attachments/assets/d553e15e-7f93-46b9-99c6-4816800e4806

### With hover (update)

https://github.com/user-attachments/assets/3812b7c5-9936-4f70-ba4d-c54cbfc1abba

### CODE REVIEW

**Comment by anth-volk** [comment]
This is looking good! One thing I'd recommend is underlining the relevant clickable portion. I'd be curious, if you don't mind, if you could work that up and share a video of it so we can see what it might look like.

**Comment by tawandamoyo** [comment]
> This is looking good! One thing I'd recommend is underlining the relevant clickable portion. I'd be curious, if you don't mind, if you could work that up and share a video of it so we can see what it might look like.

This is what it looks like with underline. 

underline

**Comment by anth-volk** [comment]
Wow, that does not look good haha. I think it'd be great to somehow indicate to the user that these lines of text are clickable, but it not be ugly. Any ideas?

**Comment by anth-volk** [comment]
Would you mind trying that out and recording it to see how it looks? In the `style` or `styles` folder, there are a series of color constants that I think would be best to utilize here.

**Comment by tawandamoyo** [comment]
> Would you mind trying that out and recording it to see how it looks? In the `style` or `styles` folder, there are a series of color constants that I think would be best to utilize here.

here with hover:

https://github.com/user-attachments/assets/bc7dd3cc-db49-4487-937f-a9aa9e891ecc

**Comment by anth-volk** [comment]
Would you mind making this so the following is true:
* The highlighting doesn't extend beyond the top or bottom of the words
* The color is a pale version of one of our blues, as opposed to gray
* The hovering doesn't move the text around; right now, when you hover, it shifts everything else downward, too

Thanks for your continued work on this, @tawandamoyo!

**Comment by tawandamoyo** [comment]
> Would you mind making this so the following is true:
> 
> * The highlighting doesn't extend beyond the top or bottom of the words
> * The color is a pale version of one of our blues, as opposed to gray
> * The hovering doesn't move the text around; right now, when you hover, it shifts everything else downward, too
> 
> Thanks for your continued work on this, @tawandamoyo!


https://github.com/user-attachments/assets/29221779-f1a3-4053-b29a-a4b29725929b

**Comment by anth-volk** [comment]
Thanks for this @tawandamoyo, it's looking good. If you feel this is ready, could you move it out of draft? And I'd just love confirmation on the design from @MaxGhenis, as he is much more user-facing, before reviewing/approving.

**Comment by anth-volk** [comment]
@MaxGhenis Hoping for your opinion on this

**Comment by MaxGhenis** [comment]
I like it! Could we bold the text on hover? We do that for other similar elements like the left menus.

**Review by anth-volk — APPROVED** [review]
Thanks for this @tawandamoyo, and my apologies for the very long delay in reviewing. This looks great!

**Pull request merged**
