### PR TITLE
adding Canada to locationLabels in postTransformers.js file

### LINKED ISSUE #1590: Add "Canada" to the `locationLabels` within `postTransformers.js`
This should mirror the other labels within that object, such as US, where a `us` key corresponds to the country's full name. Here, `ca` should correspond with `"Canada"`.

### PR DESCRIPTION
**Pull request by JoaquinFioriti**
## Description
Fixes #1590 
## Fixes 
I have added in postTransformers.js file the canada prefix to the locationLabels

### CODE REVIEW

**Comment by anth-volk** [comment]
Before I review, could you fill out the PR description, including a line saying "Fixes #<issue number>"? Thanks @JoaquinFioriti!

**Comment by JoaquinFioriti** [comment]
Done! thx

**Comment by anth-volk** [comment]
Evidently, if you put a value in brackets, like `<value>`, it gets hidden in markdown, so what I meant to write above was:

`
Before I review, could you fill out the PR description, including a line saying "Fixes #<issue number>"? Thanks @JoaquinFioriti!
`

I edited the above to reflect it.

**Comment by JoaquinFioriti** [comment]
> Evidently, if you put a value in brackets, like `<value>`, it gets hidden in markdown, so what I meant to write above was:
> 
> `Before I review, could you fill out the PR description, including a line saying "Fixes #<issue number>"? Thanks @JoaquinFioriti!`
> 
> I edited the above to reflect it.

Done! sorry for that

**Comment by anth-volk** [comment]
That's alright, apologies for the confusion. Will review probably Monday.

**Review by anth-volk — APPROVED** [review]
Thanks for this, @JoaquinFioriti! Your help is much appreciated. Approved.

**Pull request merged**
