### PR TITLE
[#377] fix/refactored show prompt using react collapse

### PR DESCRIPTION
**Pull request by sra1kumar-NULL**
Fix for : #377 

Solution Approach :
Used react collapse package only as chat gpt suggested and refactored the code for show prompt.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks! Please check out the CI failure and include a screencap video showing it in action

**Comment by sra1kumar-NULL** [comment]
> Thanks! Please check out the CI failure and include a screencap video showing it in action

fixed the ci failure issues  and here is the screen capture video 

https://user-images.githubusercontent.com/62778911/228280575-c9d5ba94-e6b2-4a74-a77d-1c3483f23e33.mp4

**Comment by MaxGhenis** [comment]
Hmm this looks the same. I was thinking of some UI component other than a button that more clearly suggests it's collapsible.

**Comment by sra1kumar-NULL** [comment]
> Hmm this looks the same. I was thinking of some UI component other than a button that more clearly suggests it's collapsible.

Do you want me to extract this  into another component @MaxGhenis

**Comment by MaxGhenis** [comment]
Yeah could you look around for some other UI options for "drawers" like this?

**Comment by MaxGhenis** [comment]
Closing for staleness but please feel free to reopen if you'd like to continue. Thanks @sra1kumar-NULL

**Pull request closed without merging**
