### PR TITLE
fix: added a copy button at top right corner

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

fixes: #1247 

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/46224156/8d9c758c-6055-43be-97d4-2d1463971169

### CODE REVIEW

**Comment by dotslashbit** [comment]
@anth-volk as Max suggested I have added the copy button exactly the way chatGPT copy works.
But I haven't removed the copy button from the bottom, I thought I should ask you first before removing it. Please, let me know your thoughts, thanks

**Comment by MaxGhenis** [comment]
This looks great to me! I think we can remove the separate button at the bottom

**Comment by MaxGhenis** [comment]
Though could we use one of the colors from our palette instead of this green? Maybe the teal?

**Comment by dotslashbit** [comment]
Screenshot 2024-01-23 at 2 05 21 AM

**Comment by dotslashbit** [comment]
I have removed the copy button from the bottom and also changed the color to TEAL_ACCENT

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
